// Auto-generated dispatch tables for KinematicsSolver
#pragma once
#include <cstddef>
#include <Eigen/Dense>

class KinematicsSolver{
public:
  // メンバ関数ポインタ型
  using Mfn = double (KinematicsSolver::*)();
  // 自動生成
  #include "generated/func.txt"

  // --- 27x27 系 ---
  Eigen::Matrix<double,27,27> Cxi_mat();
  Eigen::Matrix<double,27,27> Mxi_mat();
  Eigen::Matrix<double,18,27> Axi_mat();   
  
  // --- ベクトル系 ---
  Eigen::Matrix<double,27,1>  Kxi_vec();
  Eigen::Matrix<double,12,1>  pd_ud_vec();
  Eigen::Matrix<double,27,1>  aqd_vec();

  // --- 状態・派生 ---
  Eigen::Matrix<double,23,12> SX_mat();
  Eigen::Matrix<double,23,12> dSXdt_mat();

  inline double Cxi_rc(size_t r, size_t c) { return (this->*Cxi_tbl[r][c])(); }
  inline double Cxi(size_t i) { return (this->*Cxi_tbl[i/27][i%27])(); }
  inline double Mxi_rc(size_t r, size_t c) { return (this->*Mxi_tbl[r][c])(); }
  inline double Mxi(size_t i) { return (this->*Mxi_tbl[i/27][i%27])(); }
  inline double Axi_rc(size_t r, size_t c) { return (this->*Axi_tbl[r][c])(); }
  inline double Axi(size_t i) { return (this->*Axi_tbl[i/27][i%27])(); }
  inline double Kxi(size_t i) { return (this->*Kxi_tbl[i])(); }
  inline double SX_rc(size_t r, size_t c) { return (this->*SX_tbl[r][c])(); }
  inline double SX(size_t i) { return (this->*SX_tbl[i/12][i%12])(); }
  inline double dSXdt_rc(size_t r, size_t c) { return (this->*dSXdt_tbl[r][c])(); }
  inline double dSXdt(size_t i) { return (this->*dSXdt_tbl[i/12][i%12])(); }
  inline double pdud(size_t i) { return (this->*pdud_tbl[i])(); }
  inline double aqd(size_t i) { return (this->*aqd_tbl[i])(); }


  // --- Cxi 27x27 ---
  inline static constexpr Mfn Cxi_tbl[27][27] = {
    { &KinematicsSolver::calc_Cxi_1_1_, &KinematicsSolver::calc_Cxi_1_2_, &KinematicsSolver::calc_Cxi_1_3_, &KinematicsSolver::calc_Cxi_1_4_, &KinematicsSolver::calc_Cxi_1_5_, &KinematicsSolver::calc_Cxi_1_6_, &KinematicsSolver::calc_Cxi_1_7_, &KinematicsSolver::calc_Cxi_1_8_, &KinematicsSolver::calc_Cxi_1_9_, &KinematicsSolver::calc_Cxi_1_10_, &KinematicsSolver::calc_Cxi_1_11_, &KinematicsSolver::calc_Cxi_1_12_, &KinematicsSolver::calc_Cxi_1_13_, &KinematicsSolver::calc_Cxi_1_14_, &KinematicsSolver::calc_Cxi_1_15_, &KinematicsSolver::calc_Cxi_1_16_, &KinematicsSolver::calc_Cxi_1_17_, &KinematicsSolver::calc_Cxi_1_18_, &KinematicsSolver::calc_Cxi_1_19_, &KinematicsSolver::calc_Cxi_1_20_, &KinematicsSolver::calc_Cxi_1_21_, &KinematicsSolver::calc_Cxi_1_22_, &KinematicsSolver::calc_Cxi_1_23_, &KinematicsSolver::calc_Cxi_1_24_, &KinematicsSolver::calc_Cxi_1_25_, &KinematicsSolver::calc_Cxi_1_26_, &KinematicsSolver::calc_Cxi_1_27_ },
    { &KinematicsSolver::calc_Cxi_2_1_, &KinematicsSolver::calc_Cxi_2_2_, &KinematicsSolver::calc_Cxi_2_3_, &KinematicsSolver::calc_Cxi_2_4_, &KinematicsSolver::calc_Cxi_2_5_, &KinematicsSolver::calc_Cxi_2_6_, &KinematicsSolver::calc_Cxi_2_7_, &KinematicsSolver::calc_Cxi_2_8_, &KinematicsSolver::calc_Cxi_2_9_, &KinematicsSolver::calc_Cxi_2_10_, &KinematicsSolver::calc_Cxi_2_11_, &KinematicsSolver::calc_Cxi_2_12_, &KinematicsSolver::calc_Cxi_2_13_, &KinematicsSolver::calc_Cxi_2_14_, &KinematicsSolver::calc_Cxi_2_15_, &KinematicsSolver::calc_Cxi_2_16_, &KinematicsSolver::calc_Cxi_2_17_, &KinematicsSolver::calc_Cxi_2_18_, &KinematicsSolver::calc_Cxi_2_19_, &KinematicsSolver::calc_Cxi_2_20_, &KinematicsSolver::calc_Cxi_2_21_, &KinematicsSolver::calc_Cxi_2_22_, &KinematicsSolver::calc_Cxi_2_23_, &KinematicsSolver::calc_Cxi_2_24_, &KinematicsSolver::calc_Cxi_2_25_, &KinematicsSolver::calc_Cxi_2_26_, &KinematicsSolver::calc_Cxi_2_27_ },
    { &KinematicsSolver::calc_Cxi_3_1_, &KinematicsSolver::calc_Cxi_3_2_, &KinematicsSolver::calc_Cxi_3_3_, &KinematicsSolver::calc_Cxi_3_4_, &KinematicsSolver::calc_Cxi_3_5_, &KinematicsSolver::calc_Cxi_3_6_, &KinematicsSolver::calc_Cxi_3_7_, &KinematicsSolver::calc_Cxi_3_8_, &KinematicsSolver::calc_Cxi_3_9_, &KinematicsSolver::calc_Cxi_3_10_, &KinematicsSolver::calc_Cxi_3_11_, &KinematicsSolver::calc_Cxi_3_12_, &KinematicsSolver::calc_Cxi_3_13_, &KinematicsSolver::calc_Cxi_3_14_, &KinematicsSolver::calc_Cxi_3_15_, &KinematicsSolver::calc_Cxi_3_16_, &KinematicsSolver::calc_Cxi_3_17_, &KinematicsSolver::calc_Cxi_3_18_, &KinematicsSolver::calc_Cxi_3_19_, &KinematicsSolver::calc_Cxi_3_20_, &KinematicsSolver::calc_Cxi_3_21_, &KinematicsSolver::calc_Cxi_3_22_, &KinematicsSolver::calc_Cxi_3_23_, &KinematicsSolver::calc_Cxi_3_24_, &KinematicsSolver::calc_Cxi_3_25_, &KinematicsSolver::calc_Cxi_3_26_, &KinematicsSolver::calc_Cxi_3_27_ },
    { &KinematicsSolver::calc_Cxi_4_1_, &KinematicsSolver::calc_Cxi_4_2_, &KinematicsSolver::calc_Cxi_4_3_, &KinematicsSolver::calc_Cxi_4_4_, &KinematicsSolver::calc_Cxi_4_5_, &KinematicsSolver::calc_Cxi_4_6_, &KinematicsSolver::calc_Cxi_4_7_, &KinematicsSolver::calc_Cxi_4_8_, &KinematicsSolver::calc_Cxi_4_9_, &KinematicsSolver::calc_Cxi_4_10_, &KinematicsSolver::calc_Cxi_4_11_, &KinematicsSolver::calc_Cxi_4_12_, &KinematicsSolver::calc_Cxi_4_13_, &KinematicsSolver::calc_Cxi_4_14_, &KinematicsSolver::calc_Cxi_4_15_, &KinematicsSolver::calc_Cxi_4_16_, &KinematicsSolver::calc_Cxi_4_17_, &KinematicsSolver::calc_Cxi_4_18_, &KinematicsSolver::calc_Cxi_4_19_, &KinematicsSolver::calc_Cxi_4_20_, &KinematicsSolver::calc_Cxi_4_21_, &KinematicsSolver::calc_Cxi_4_22_, &KinematicsSolver::calc_Cxi_4_23_, &KinematicsSolver::calc_Cxi_4_24_, &KinematicsSolver::calc_Cxi_4_25_, &KinematicsSolver::calc_Cxi_4_26_, &KinematicsSolver::calc_Cxi_4_27_ },
    { &KinematicsSolver::calc_Cxi_5_1_, &KinematicsSolver::calc_Cxi_5_2_, &KinematicsSolver::calc_Cxi_5_3_, &KinematicsSolver::calc_Cxi_5_4_, &KinematicsSolver::calc_Cxi_5_5_, &KinematicsSolver::calc_Cxi_5_6_, &KinematicsSolver::calc_Cxi_5_7_, &KinematicsSolver::calc_Cxi_5_8_, &KinematicsSolver::calc_Cxi_5_9_, &KinematicsSolver::calc_Cxi_5_10_, &KinematicsSolver::calc_Cxi_5_11_, &KinematicsSolver::calc_Cxi_5_12_, &KinematicsSolver::calc_Cxi_5_13_, &KinematicsSolver::calc_Cxi_5_14_, &KinematicsSolver::calc_Cxi_5_15_, &KinematicsSolver::calc_Cxi_5_16_, &KinematicsSolver::calc_Cxi_5_17_, &KinematicsSolver::calc_Cxi_5_18_, &KinematicsSolver::calc_Cxi_5_19_, &KinematicsSolver::calc_Cxi_5_20_, &KinematicsSolver::calc_Cxi_5_21_, &KinematicsSolver::calc_Cxi_5_22_, &KinematicsSolver::calc_Cxi_5_23_, &KinematicsSolver::calc_Cxi_5_24_, &KinematicsSolver::calc_Cxi_5_25_, &KinematicsSolver::calc_Cxi_5_26_, &KinematicsSolver::calc_Cxi_5_27_ },
    { &KinematicsSolver::calc_Cxi_6_1_, &KinematicsSolver::calc_Cxi_6_2_, &KinematicsSolver::calc_Cxi_6_3_, &KinematicsSolver::calc_Cxi_6_4_, &KinematicsSolver::calc_Cxi_6_5_, &KinematicsSolver::calc_Cxi_6_6_, &KinematicsSolver::calc_Cxi_6_7_, &KinematicsSolver::calc_Cxi_6_8_, &KinematicsSolver::calc_Cxi_6_9_, &KinematicsSolver::calc_Cxi_6_10_, &KinematicsSolver::calc_Cxi_6_11_, &KinematicsSolver::calc_Cxi_6_12_, &KinematicsSolver::calc_Cxi_6_13_, &KinematicsSolver::calc_Cxi_6_14_, &KinematicsSolver::calc_Cxi_6_15_, &KinematicsSolver::calc_Cxi_6_16_, &KinematicsSolver::calc_Cxi_6_17_, &KinematicsSolver::calc_Cxi_6_18_, &KinematicsSolver::calc_Cxi_6_19_, &KinematicsSolver::calc_Cxi_6_20_, &KinematicsSolver::calc_Cxi_6_21_, &KinematicsSolver::calc_Cxi_6_22_, &KinematicsSolver::calc_Cxi_6_23_, &KinematicsSolver::calc_Cxi_6_24_, &KinematicsSolver::calc_Cxi_6_25_, &KinematicsSolver::calc_Cxi_6_26_, &KinematicsSolver::calc_Cxi_6_27_ },
    { &KinematicsSolver::calc_Cxi_7_1_, &KinematicsSolver::calc_Cxi_7_2_, &KinematicsSolver::calc_Cxi_7_3_, &KinematicsSolver::calc_Cxi_7_4_, &KinematicsSolver::calc_Cxi_7_5_, &KinematicsSolver::calc_Cxi_7_6_, &KinematicsSolver::calc_Cxi_7_7_, &KinematicsSolver::calc_Cxi_7_8_, &KinematicsSolver::calc_Cxi_7_9_, &KinematicsSolver::calc_Cxi_7_10_, &KinematicsSolver::calc_Cxi_7_11_, &KinematicsSolver::calc_Cxi_7_12_, &KinematicsSolver::calc_Cxi_7_13_, &KinematicsSolver::calc_Cxi_7_14_, &KinematicsSolver::calc_Cxi_7_15_, &KinematicsSolver::calc_Cxi_7_16_, &KinematicsSolver::calc_Cxi_7_17_, &KinematicsSolver::calc_Cxi_7_18_, &KinematicsSolver::calc_Cxi_7_19_, &KinematicsSolver::calc_Cxi_7_20_, &KinematicsSolver::calc_Cxi_7_21_, &KinematicsSolver::calc_Cxi_7_22_, &KinematicsSolver::calc_Cxi_7_23_, &KinematicsSolver::calc_Cxi_7_24_, &KinematicsSolver::calc_Cxi_7_25_, &KinematicsSolver::calc_Cxi_7_26_, &KinematicsSolver::calc_Cxi_7_27_ },
    { &KinematicsSolver::calc_Cxi_8_1_, &KinematicsSolver::calc_Cxi_8_2_, &KinematicsSolver::calc_Cxi_8_3_, &KinematicsSolver::calc_Cxi_8_4_, &KinematicsSolver::calc_Cxi_8_5_, &KinematicsSolver::calc_Cxi_8_6_, &KinematicsSolver::calc_Cxi_8_7_, &KinematicsSolver::calc_Cxi_8_8_, &KinematicsSolver::calc_Cxi_8_9_, &KinematicsSolver::calc_Cxi_8_10_, &KinematicsSolver::calc_Cxi_8_11_, &KinematicsSolver::calc_Cxi_8_12_, &KinematicsSolver::calc_Cxi_8_13_, &KinematicsSolver::calc_Cxi_8_14_, &KinematicsSolver::calc_Cxi_8_15_, &KinematicsSolver::calc_Cxi_8_16_, &KinematicsSolver::calc_Cxi_8_17_, &KinematicsSolver::calc_Cxi_8_18_, &KinematicsSolver::calc_Cxi_8_19_, &KinematicsSolver::calc_Cxi_8_20_, &KinematicsSolver::calc_Cxi_8_21_, &KinematicsSolver::calc_Cxi_8_22_, &KinematicsSolver::calc_Cxi_8_23_, &KinematicsSolver::calc_Cxi_8_24_, &KinematicsSolver::calc_Cxi_8_25_, &KinematicsSolver::calc_Cxi_8_26_, &KinematicsSolver::calc_Cxi_8_27_ },
    { &KinematicsSolver::calc_Cxi_9_1_, &KinematicsSolver::calc_Cxi_9_2_, &KinematicsSolver::calc_Cxi_9_3_, &KinematicsSolver::calc_Cxi_9_4_, &KinematicsSolver::calc_Cxi_9_5_, &KinematicsSolver::calc_Cxi_9_6_, &KinematicsSolver::calc_Cxi_9_7_, &KinematicsSolver::calc_Cxi_9_8_, &KinematicsSolver::calc_Cxi_9_9_, &KinematicsSolver::calc_Cxi_9_10_, &KinematicsSolver::calc_Cxi_9_11_, &KinematicsSolver::calc_Cxi_9_12_, &KinematicsSolver::calc_Cxi_9_13_, &KinematicsSolver::calc_Cxi_9_14_, &KinematicsSolver::calc_Cxi_9_15_, &KinematicsSolver::calc_Cxi_9_16_, &KinematicsSolver::calc_Cxi_9_17_, &KinematicsSolver::calc_Cxi_9_18_, &KinematicsSolver::calc_Cxi_9_19_, &KinematicsSolver::calc_Cxi_9_20_, &KinematicsSolver::calc_Cxi_9_21_, &KinematicsSolver::calc_Cxi_9_22_, &KinematicsSolver::calc_Cxi_9_23_, &KinematicsSolver::calc_Cxi_9_24_, &KinematicsSolver::calc_Cxi_9_25_, &KinematicsSolver::calc_Cxi_9_26_, &KinematicsSolver::calc_Cxi_9_27_ },
    { &KinematicsSolver::calc_Cxi_10_1_, &KinematicsSolver::calc_Cxi_10_2_, &KinematicsSolver::calc_Cxi_10_3_, &KinematicsSolver::calc_Cxi_10_4_, &KinematicsSolver::calc_Cxi_10_5_, &KinematicsSolver::calc_Cxi_10_6_, &KinematicsSolver::calc_Cxi_10_7_, &KinematicsSolver::calc_Cxi_10_8_, &KinematicsSolver::calc_Cxi_10_9_, &KinematicsSolver::calc_Cxi_10_10_, &KinematicsSolver::calc_Cxi_10_11_, &KinematicsSolver::calc_Cxi_10_12_, &KinematicsSolver::calc_Cxi_10_13_, &KinematicsSolver::calc_Cxi_10_14_, &KinematicsSolver::calc_Cxi_10_15_, &KinematicsSolver::calc_Cxi_10_16_, &KinematicsSolver::calc_Cxi_10_17_, &KinematicsSolver::calc_Cxi_10_18_, &KinematicsSolver::calc_Cxi_10_19_, &KinematicsSolver::calc_Cxi_10_20_, &KinematicsSolver::calc_Cxi_10_21_, &KinematicsSolver::calc_Cxi_10_22_, &KinematicsSolver::calc_Cxi_10_23_, &KinematicsSolver::calc_Cxi_10_24_, &KinematicsSolver::calc_Cxi_10_25_, &KinematicsSolver::calc_Cxi_10_26_, &KinematicsSolver::calc_Cxi_10_27_ },
    { &KinematicsSolver::calc_Cxi_11_1_, &KinematicsSolver::calc_Cxi_11_2_, &KinematicsSolver::calc_Cxi_11_3_, &KinematicsSolver::calc_Cxi_11_4_, &KinematicsSolver::calc_Cxi_11_5_, &KinematicsSolver::calc_Cxi_11_6_, &KinematicsSolver::calc_Cxi_11_7_, &KinematicsSolver::calc_Cxi_11_8_, &KinematicsSolver::calc_Cxi_11_9_, &KinematicsSolver::calc_Cxi_11_10_, &KinematicsSolver::calc_Cxi_11_11_, &KinematicsSolver::calc_Cxi_11_12_, &KinematicsSolver::calc_Cxi_11_13_, &KinematicsSolver::calc_Cxi_11_14_, &KinematicsSolver::calc_Cxi_11_15_, &KinematicsSolver::calc_Cxi_11_16_, &KinematicsSolver::calc_Cxi_11_17_, &KinematicsSolver::calc_Cxi_11_18_, &KinematicsSolver::calc_Cxi_11_19_, &KinematicsSolver::calc_Cxi_11_20_, &KinematicsSolver::calc_Cxi_11_21_, &KinematicsSolver::calc_Cxi_11_22_, &KinematicsSolver::calc_Cxi_11_23_, &KinematicsSolver::calc_Cxi_11_24_, &KinematicsSolver::calc_Cxi_11_25_, &KinematicsSolver::calc_Cxi_11_26_, &KinematicsSolver::calc_Cxi_11_27_ },
    { &KinematicsSolver::calc_Cxi_12_1_, &KinematicsSolver::calc_Cxi_12_2_, &KinematicsSolver::calc_Cxi_12_3_, &KinematicsSolver::calc_Cxi_12_4_, &KinematicsSolver::calc_Cxi_12_5_, &KinematicsSolver::calc_Cxi_12_6_, &KinematicsSolver::calc_Cxi_12_7_, &KinematicsSolver::calc_Cxi_12_8_, &KinematicsSolver::calc_Cxi_12_9_, &KinematicsSolver::calc_Cxi_12_10_, &KinematicsSolver::calc_Cxi_12_11_, &KinematicsSolver::calc_Cxi_12_12_, &KinematicsSolver::calc_Cxi_12_13_, &KinematicsSolver::calc_Cxi_12_14_, &KinematicsSolver::calc_Cxi_12_15_, &KinematicsSolver::calc_Cxi_12_16_, &KinematicsSolver::calc_Cxi_12_17_, &KinematicsSolver::calc_Cxi_12_18_, &KinematicsSolver::calc_Cxi_12_19_, &KinematicsSolver::calc_Cxi_12_20_, &KinematicsSolver::calc_Cxi_12_21_, &KinematicsSolver::calc_Cxi_12_22_, &KinematicsSolver::calc_Cxi_12_23_, &KinematicsSolver::calc_Cxi_12_24_, &KinematicsSolver::calc_Cxi_12_25_, &KinematicsSolver::calc_Cxi_12_26_, &KinematicsSolver::calc_Cxi_12_27_ },
    { &KinematicsSolver::calc_Cxi_13_1_, &KinematicsSolver::calc_Cxi_13_2_, &KinematicsSolver::calc_Cxi_13_3_, &KinematicsSolver::calc_Cxi_13_4_, &KinematicsSolver::calc_Cxi_13_5_, &KinematicsSolver::calc_Cxi_13_6_, &KinematicsSolver::calc_Cxi_13_7_, &KinematicsSolver::calc_Cxi_13_8_, &KinematicsSolver::calc_Cxi_13_9_, &KinematicsSolver::calc_Cxi_13_10_, &KinematicsSolver::calc_Cxi_13_11_, &KinematicsSolver::calc_Cxi_13_12_, &KinematicsSolver::calc_Cxi_13_13_, &KinematicsSolver::calc_Cxi_13_14_, &KinematicsSolver::calc_Cxi_13_15_, &KinematicsSolver::calc_Cxi_13_16_, &KinematicsSolver::calc_Cxi_13_17_, &KinematicsSolver::calc_Cxi_13_18_, &KinematicsSolver::calc_Cxi_13_19_, &KinematicsSolver::calc_Cxi_13_20_, &KinematicsSolver::calc_Cxi_13_21_, &KinematicsSolver::calc_Cxi_13_22_, &KinematicsSolver::calc_Cxi_13_23_, &KinematicsSolver::calc_Cxi_13_24_, &KinematicsSolver::calc_Cxi_13_25_, &KinematicsSolver::calc_Cxi_13_26_, &KinematicsSolver::calc_Cxi_13_27_ },
    { &KinematicsSolver::calc_Cxi_14_1_, &KinematicsSolver::calc_Cxi_14_2_, &KinematicsSolver::calc_Cxi_14_3_, &KinematicsSolver::calc_Cxi_14_4_, &KinematicsSolver::calc_Cxi_14_5_, &KinematicsSolver::calc_Cxi_14_6_, &KinematicsSolver::calc_Cxi_14_7_, &KinematicsSolver::calc_Cxi_14_8_, &KinematicsSolver::calc_Cxi_14_9_, &KinematicsSolver::calc_Cxi_14_10_, &KinematicsSolver::calc_Cxi_14_11_, &KinematicsSolver::calc_Cxi_14_12_, &KinematicsSolver::calc_Cxi_14_13_, &KinematicsSolver::calc_Cxi_14_14_, &KinematicsSolver::calc_Cxi_14_15_, &KinematicsSolver::calc_Cxi_14_16_, &KinematicsSolver::calc_Cxi_14_17_, &KinematicsSolver::calc_Cxi_14_18_, &KinematicsSolver::calc_Cxi_14_19_, &KinematicsSolver::calc_Cxi_14_20_, &KinematicsSolver::calc_Cxi_14_21_, &KinematicsSolver::calc_Cxi_14_22_, &KinematicsSolver::calc_Cxi_14_23_, &KinematicsSolver::calc_Cxi_14_24_, &KinematicsSolver::calc_Cxi_14_25_, &KinematicsSolver::calc_Cxi_14_26_, &KinematicsSolver::calc_Cxi_14_27_ },
    { &KinematicsSolver::calc_Cxi_15_1_, &KinematicsSolver::calc_Cxi_15_2_, &KinematicsSolver::calc_Cxi_15_3_, &KinematicsSolver::calc_Cxi_15_4_, &KinematicsSolver::calc_Cxi_15_5_, &KinematicsSolver::calc_Cxi_15_6_, &KinematicsSolver::calc_Cxi_15_7_, &KinematicsSolver::calc_Cxi_15_8_, &KinematicsSolver::calc_Cxi_15_9_, &KinematicsSolver::calc_Cxi_15_10_, &KinematicsSolver::calc_Cxi_15_11_, &KinematicsSolver::calc_Cxi_15_12_, &KinematicsSolver::calc_Cxi_15_13_, &KinematicsSolver::calc_Cxi_15_14_, &KinematicsSolver::calc_Cxi_15_15_, &KinematicsSolver::calc_Cxi_15_16_, &KinematicsSolver::calc_Cxi_15_17_, &KinematicsSolver::calc_Cxi_15_18_, &KinematicsSolver::calc_Cxi_15_19_, &KinematicsSolver::calc_Cxi_15_20_, &KinematicsSolver::calc_Cxi_15_21_, &KinematicsSolver::calc_Cxi_15_22_, &KinematicsSolver::calc_Cxi_15_23_, &KinematicsSolver::calc_Cxi_15_24_, &KinematicsSolver::calc_Cxi_15_25_, &KinematicsSolver::calc_Cxi_15_26_, &KinematicsSolver::calc_Cxi_15_27_ },
    { &KinematicsSolver::calc_Cxi_16_1_, &KinematicsSolver::calc_Cxi_16_2_, &KinematicsSolver::calc_Cxi_16_3_, &KinematicsSolver::calc_Cxi_16_4_, &KinematicsSolver::calc_Cxi_16_5_, &KinematicsSolver::calc_Cxi_16_6_, &KinematicsSolver::calc_Cxi_16_7_, &KinematicsSolver::calc_Cxi_16_8_, &KinematicsSolver::calc_Cxi_16_9_, &KinematicsSolver::calc_Cxi_16_10_, &KinematicsSolver::calc_Cxi_16_11_, &KinematicsSolver::calc_Cxi_16_12_, &KinematicsSolver::calc_Cxi_16_13_, &KinematicsSolver::calc_Cxi_16_14_, &KinematicsSolver::calc_Cxi_16_15_, &KinematicsSolver::calc_Cxi_16_16_, &KinematicsSolver::calc_Cxi_16_17_, &KinematicsSolver::calc_Cxi_16_18_, &KinematicsSolver::calc_Cxi_16_19_, &KinematicsSolver::calc_Cxi_16_20_, &KinematicsSolver::calc_Cxi_16_21_, &KinematicsSolver::calc_Cxi_16_22_, &KinematicsSolver::calc_Cxi_16_23_, &KinematicsSolver::calc_Cxi_16_24_, &KinematicsSolver::calc_Cxi_16_25_, &KinematicsSolver::calc_Cxi_16_26_, &KinematicsSolver::calc_Cxi_16_27_ },
    { &KinematicsSolver::calc_Cxi_17_1_, &KinematicsSolver::calc_Cxi_17_2_, &KinematicsSolver::calc_Cxi_17_3_, &KinematicsSolver::calc_Cxi_17_4_, &KinematicsSolver::calc_Cxi_17_5_, &KinematicsSolver::calc_Cxi_17_6_, &KinematicsSolver::calc_Cxi_17_7_, &KinematicsSolver::calc_Cxi_17_8_, &KinematicsSolver::calc_Cxi_17_9_, &KinematicsSolver::calc_Cxi_17_10_, &KinematicsSolver::calc_Cxi_17_11_, &KinematicsSolver::calc_Cxi_17_12_, &KinematicsSolver::calc_Cxi_17_13_, &KinematicsSolver::calc_Cxi_17_14_, &KinematicsSolver::calc_Cxi_17_15_, &KinematicsSolver::calc_Cxi_17_16_, &KinematicsSolver::calc_Cxi_17_17_, &KinematicsSolver::calc_Cxi_17_18_, &KinematicsSolver::calc_Cxi_17_19_, &KinematicsSolver::calc_Cxi_17_20_, &KinematicsSolver::calc_Cxi_17_21_, &KinematicsSolver::calc_Cxi_17_22_, &KinematicsSolver::calc_Cxi_17_23_, &KinematicsSolver::calc_Cxi_17_24_, &KinematicsSolver::calc_Cxi_17_25_, &KinematicsSolver::calc_Cxi_17_26_, &KinematicsSolver::calc_Cxi_17_27_ },
    { &KinematicsSolver::calc_Cxi_18_1_, &KinematicsSolver::calc_Cxi_18_2_, &KinematicsSolver::calc_Cxi_18_3_, &KinematicsSolver::calc_Cxi_18_4_, &KinematicsSolver::calc_Cxi_18_5_, &KinematicsSolver::calc_Cxi_18_6_, &KinematicsSolver::calc_Cxi_18_7_, &KinematicsSolver::calc_Cxi_18_8_, &KinematicsSolver::calc_Cxi_18_9_, &KinematicsSolver::calc_Cxi_18_10_, &KinematicsSolver::calc_Cxi_18_11_, &KinematicsSolver::calc_Cxi_18_12_, &KinematicsSolver::calc_Cxi_18_13_, &KinematicsSolver::calc_Cxi_18_14_, &KinematicsSolver::calc_Cxi_18_15_, &KinematicsSolver::calc_Cxi_18_16_, &KinematicsSolver::calc_Cxi_18_17_, &KinematicsSolver::calc_Cxi_18_18_, &KinematicsSolver::calc_Cxi_18_19_, &KinematicsSolver::calc_Cxi_18_20_, &KinematicsSolver::calc_Cxi_18_21_, &KinematicsSolver::calc_Cxi_18_22_, &KinematicsSolver::calc_Cxi_18_23_, &KinematicsSolver::calc_Cxi_18_24_, &KinematicsSolver::calc_Cxi_18_25_, &KinematicsSolver::calc_Cxi_18_26_, &KinematicsSolver::calc_Cxi_18_27_ },
    { &KinematicsSolver::calc_Cxi_19_1_, &KinematicsSolver::calc_Cxi_19_2_, &KinematicsSolver::calc_Cxi_19_3_, &KinematicsSolver::calc_Cxi_19_4_, &KinematicsSolver::calc_Cxi_19_5_, &KinematicsSolver::calc_Cxi_19_6_, &KinematicsSolver::calc_Cxi_19_7_, &KinematicsSolver::calc_Cxi_19_8_, &KinematicsSolver::calc_Cxi_19_9_, &KinematicsSolver::calc_Cxi_19_10_, &KinematicsSolver::calc_Cxi_19_11_, &KinematicsSolver::calc_Cxi_19_12_, &KinematicsSolver::calc_Cxi_19_13_, &KinematicsSolver::calc_Cxi_19_14_, &KinematicsSolver::calc_Cxi_19_15_, &KinematicsSolver::calc_Cxi_19_16_, &KinematicsSolver::calc_Cxi_19_17_, &KinematicsSolver::calc_Cxi_19_18_, &KinematicsSolver::calc_Cxi_19_19_, &KinematicsSolver::calc_Cxi_19_20_, &KinematicsSolver::calc_Cxi_19_21_, &KinematicsSolver::calc_Cxi_19_22_, &KinematicsSolver::calc_Cxi_19_23_, &KinematicsSolver::calc_Cxi_19_24_, &KinematicsSolver::calc_Cxi_19_25_, &KinematicsSolver::calc_Cxi_19_26_, &KinematicsSolver::calc_Cxi_19_27_ },
    { &KinematicsSolver::calc_Cxi_20_1_, &KinematicsSolver::calc_Cxi_20_2_, &KinematicsSolver::calc_Cxi_20_3_, &KinematicsSolver::calc_Cxi_20_4_, &KinematicsSolver::calc_Cxi_20_5_, &KinematicsSolver::calc_Cxi_20_6_, &KinematicsSolver::calc_Cxi_20_7_, &KinematicsSolver::calc_Cxi_20_8_, &KinematicsSolver::calc_Cxi_20_9_, &KinematicsSolver::calc_Cxi_20_10_, &KinematicsSolver::calc_Cxi_20_11_, &KinematicsSolver::calc_Cxi_20_12_, &KinematicsSolver::calc_Cxi_20_13_, &KinematicsSolver::calc_Cxi_20_14_, &KinematicsSolver::calc_Cxi_20_15_, &KinematicsSolver::calc_Cxi_20_16_, &KinematicsSolver::calc_Cxi_20_17_, &KinematicsSolver::calc_Cxi_20_18_, &KinematicsSolver::calc_Cxi_20_19_, &KinematicsSolver::calc_Cxi_20_20_, &KinematicsSolver::calc_Cxi_20_21_, &KinematicsSolver::calc_Cxi_20_22_, &KinematicsSolver::calc_Cxi_20_23_, &KinematicsSolver::calc_Cxi_20_24_, &KinematicsSolver::calc_Cxi_20_25_, &KinematicsSolver::calc_Cxi_20_26_, &KinematicsSolver::calc_Cxi_20_27_ },
    { &KinematicsSolver::calc_Cxi_21_1_, &KinematicsSolver::calc_Cxi_21_2_, &KinematicsSolver::calc_Cxi_21_3_, &KinematicsSolver::calc_Cxi_21_4_, &KinematicsSolver::calc_Cxi_21_5_, &KinematicsSolver::calc_Cxi_21_6_, &KinematicsSolver::calc_Cxi_21_7_, &KinematicsSolver::calc_Cxi_21_8_, &KinematicsSolver::calc_Cxi_21_9_, &KinematicsSolver::calc_Cxi_21_10_, &KinematicsSolver::calc_Cxi_21_11_, &KinematicsSolver::calc_Cxi_21_12_, &KinematicsSolver::calc_Cxi_21_13_, &KinematicsSolver::calc_Cxi_21_14_, &KinematicsSolver::calc_Cxi_21_15_, &KinematicsSolver::calc_Cxi_21_16_, &KinematicsSolver::calc_Cxi_21_17_, &KinematicsSolver::calc_Cxi_21_18_, &KinematicsSolver::calc_Cxi_21_19_, &KinematicsSolver::calc_Cxi_21_20_, &KinematicsSolver::calc_Cxi_21_21_, &KinematicsSolver::calc_Cxi_21_22_, &KinematicsSolver::calc_Cxi_21_23_, &KinematicsSolver::calc_Cxi_21_24_, &KinematicsSolver::calc_Cxi_21_25_, &KinematicsSolver::calc_Cxi_21_26_, &KinematicsSolver::calc_Cxi_21_27_ },
    { &KinematicsSolver::calc_Cxi_22_1_, &KinematicsSolver::calc_Cxi_22_2_, &KinematicsSolver::calc_Cxi_22_3_, &KinematicsSolver::calc_Cxi_22_4_, &KinematicsSolver::calc_Cxi_22_5_, &KinematicsSolver::calc_Cxi_22_6_, &KinematicsSolver::calc_Cxi_22_7_, &KinematicsSolver::calc_Cxi_22_8_, &KinematicsSolver::calc_Cxi_22_9_, &KinematicsSolver::calc_Cxi_22_10_, &KinematicsSolver::calc_Cxi_22_11_, &KinematicsSolver::calc_Cxi_22_12_, &KinematicsSolver::calc_Cxi_22_13_, &KinematicsSolver::calc_Cxi_22_14_, &KinematicsSolver::calc_Cxi_22_15_, &KinematicsSolver::calc_Cxi_22_16_, &KinematicsSolver::calc_Cxi_22_17_, &KinematicsSolver::calc_Cxi_22_18_, &KinematicsSolver::calc_Cxi_22_19_, &KinematicsSolver::calc_Cxi_22_20_, &KinematicsSolver::calc_Cxi_22_21_, &KinematicsSolver::calc_Cxi_22_22_, &KinematicsSolver::calc_Cxi_22_23_, &KinematicsSolver::calc_Cxi_22_24_, &KinematicsSolver::calc_Cxi_22_25_, &KinematicsSolver::calc_Cxi_22_26_, &KinematicsSolver::calc_Cxi_22_27_ },
    { &KinematicsSolver::calc_Cxi_23_1_, &KinematicsSolver::calc_Cxi_23_2_, &KinematicsSolver::calc_Cxi_23_3_, &KinematicsSolver::calc_Cxi_23_4_, &KinematicsSolver::calc_Cxi_23_5_, &KinematicsSolver::calc_Cxi_23_6_, &KinematicsSolver::calc_Cxi_23_7_, &KinematicsSolver::calc_Cxi_23_8_, &KinematicsSolver::calc_Cxi_23_9_, &KinematicsSolver::calc_Cxi_23_10_, &KinematicsSolver::calc_Cxi_23_11_, &KinematicsSolver::calc_Cxi_23_12_, &KinematicsSolver::calc_Cxi_23_13_, &KinematicsSolver::calc_Cxi_23_14_, &KinematicsSolver::calc_Cxi_23_15_, &KinematicsSolver::calc_Cxi_23_16_, &KinematicsSolver::calc_Cxi_23_17_, &KinematicsSolver::calc_Cxi_23_18_, &KinematicsSolver::calc_Cxi_23_19_, &KinematicsSolver::calc_Cxi_23_20_, &KinematicsSolver::calc_Cxi_23_21_, &KinematicsSolver::calc_Cxi_23_22_, &KinematicsSolver::calc_Cxi_23_23_, &KinematicsSolver::calc_Cxi_23_24_, &KinematicsSolver::calc_Cxi_23_25_, &KinematicsSolver::calc_Cxi_23_26_, &KinematicsSolver::calc_Cxi_23_27_ },
    { &KinematicsSolver::calc_Cxi_24_1_, &KinematicsSolver::calc_Cxi_24_2_, &KinematicsSolver::calc_Cxi_24_3_, &KinematicsSolver::calc_Cxi_24_4_, &KinematicsSolver::calc_Cxi_24_5_, &KinematicsSolver::calc_Cxi_24_6_, &KinematicsSolver::calc_Cxi_24_7_, &KinematicsSolver::calc_Cxi_24_8_, &KinematicsSolver::calc_Cxi_24_9_, &KinematicsSolver::calc_Cxi_24_10_, &KinematicsSolver::calc_Cxi_24_11_, &KinematicsSolver::calc_Cxi_24_12_, &KinematicsSolver::calc_Cxi_24_13_, &KinematicsSolver::calc_Cxi_24_14_, &KinematicsSolver::calc_Cxi_24_15_, &KinematicsSolver::calc_Cxi_24_16_, &KinematicsSolver::calc_Cxi_24_17_, &KinematicsSolver::calc_Cxi_24_18_, &KinematicsSolver::calc_Cxi_24_19_, &KinematicsSolver::calc_Cxi_24_20_, &KinematicsSolver::calc_Cxi_24_21_, &KinematicsSolver::calc_Cxi_24_22_, &KinematicsSolver::calc_Cxi_24_23_, &KinematicsSolver::calc_Cxi_24_24_, &KinematicsSolver::calc_Cxi_24_25_, &KinematicsSolver::calc_Cxi_24_26_, &KinematicsSolver::calc_Cxi_24_27_ },
    { &KinematicsSolver::calc_Cxi_25_1_, &KinematicsSolver::calc_Cxi_25_2_, &KinematicsSolver::calc_Cxi_25_3_, &KinematicsSolver::calc_Cxi_25_4_, &KinematicsSolver::calc_Cxi_25_5_, &KinematicsSolver::calc_Cxi_25_6_, &KinematicsSolver::calc_Cxi_25_7_, &KinematicsSolver::calc_Cxi_25_8_, &KinematicsSolver::calc_Cxi_25_9_, &KinematicsSolver::calc_Cxi_25_10_, &KinematicsSolver::calc_Cxi_25_11_, &KinematicsSolver::calc_Cxi_25_12_, &KinematicsSolver::calc_Cxi_25_13_, &KinematicsSolver::calc_Cxi_25_14_, &KinematicsSolver::calc_Cxi_25_15_, &KinematicsSolver::calc_Cxi_25_16_, &KinematicsSolver::calc_Cxi_25_17_, &KinematicsSolver::calc_Cxi_25_18_, &KinematicsSolver::calc_Cxi_25_19_, &KinematicsSolver::calc_Cxi_25_20_, &KinematicsSolver::calc_Cxi_25_21_, &KinematicsSolver::calc_Cxi_25_22_, &KinematicsSolver::calc_Cxi_25_23_, &KinematicsSolver::calc_Cxi_25_24_, &KinematicsSolver::calc_Cxi_25_25_, &KinematicsSolver::calc_Cxi_25_26_, &KinematicsSolver::calc_Cxi_25_27_ },
    { &KinematicsSolver::calc_Cxi_26_1_, &KinematicsSolver::calc_Cxi_26_2_, &KinematicsSolver::calc_Cxi_26_3_, &KinematicsSolver::calc_Cxi_26_4_, &KinematicsSolver::calc_Cxi_26_5_, &KinematicsSolver::calc_Cxi_26_6_, &KinematicsSolver::calc_Cxi_26_7_, &KinematicsSolver::calc_Cxi_26_8_, &KinematicsSolver::calc_Cxi_26_9_, &KinematicsSolver::calc_Cxi_26_10_, &KinematicsSolver::calc_Cxi_26_11_, &KinematicsSolver::calc_Cxi_26_12_, &KinematicsSolver::calc_Cxi_26_13_, &KinematicsSolver::calc_Cxi_26_14_, &KinematicsSolver::calc_Cxi_26_15_, &KinematicsSolver::calc_Cxi_26_16_, &KinematicsSolver::calc_Cxi_26_17_, &KinematicsSolver::calc_Cxi_26_18_, &KinematicsSolver::calc_Cxi_26_19_, &KinematicsSolver::calc_Cxi_26_20_, &KinematicsSolver::calc_Cxi_26_21_, &KinematicsSolver::calc_Cxi_26_22_, &KinematicsSolver::calc_Cxi_26_23_, &KinematicsSolver::calc_Cxi_26_24_, &KinematicsSolver::calc_Cxi_26_25_, &KinematicsSolver::calc_Cxi_26_26_, &KinematicsSolver::calc_Cxi_26_27_ },
    { &KinematicsSolver::calc_Cxi_27_1_, &KinematicsSolver::calc_Cxi_27_2_, &KinematicsSolver::calc_Cxi_27_3_, &KinematicsSolver::calc_Cxi_27_4_, &KinematicsSolver::calc_Cxi_27_5_, &KinematicsSolver::calc_Cxi_27_6_, &KinematicsSolver::calc_Cxi_27_7_, &KinematicsSolver::calc_Cxi_27_8_, &KinematicsSolver::calc_Cxi_27_9_, &KinematicsSolver::calc_Cxi_27_10_, &KinematicsSolver::calc_Cxi_27_11_, &KinematicsSolver::calc_Cxi_27_12_, &KinematicsSolver::calc_Cxi_27_13_, &KinematicsSolver::calc_Cxi_27_14_, &KinematicsSolver::calc_Cxi_27_15_, &KinematicsSolver::calc_Cxi_27_16_, &KinematicsSolver::calc_Cxi_27_17_, &KinematicsSolver::calc_Cxi_27_18_, &KinematicsSolver::calc_Cxi_27_19_, &KinematicsSolver::calc_Cxi_27_20_, &KinematicsSolver::calc_Cxi_27_21_, &KinematicsSolver::calc_Cxi_27_22_, &KinematicsSolver::calc_Cxi_27_23_, &KinematicsSolver::calc_Cxi_27_24_, &KinematicsSolver::calc_Cxi_27_25_, &KinematicsSolver::calc_Cxi_27_26_, &KinematicsSolver::calc_Cxi_27_27_ }
  };
  
  
  
  // --- Mxi 27x27 ---
  inline static constexpr Mfn Mxi_tbl[27][27] = {
    { &KinematicsSolver::calc_Mxi_1_1_, &KinematicsSolver::calc_Mxi_1_2_, &KinematicsSolver::calc_Mxi_1_3_, &KinematicsSolver::calc_Mxi_1_4_, &KinematicsSolver::calc_Mxi_1_5_, &KinematicsSolver::calc_Mxi_1_6_, &KinematicsSolver::calc_Mxi_1_7_, &KinematicsSolver::calc_Mxi_1_8_, &KinematicsSolver::calc_Mxi_1_9_, &KinematicsSolver::calc_Mxi_1_10_, &KinematicsSolver::calc_Mxi_1_11_, &KinematicsSolver::calc_Mxi_1_12_, &KinematicsSolver::calc_Mxi_1_13_, &KinematicsSolver::calc_Mxi_1_14_, &KinematicsSolver::calc_Mxi_1_15_, &KinematicsSolver::calc_Mxi_1_16_, &KinematicsSolver::calc_Mxi_1_17_, &KinematicsSolver::calc_Mxi_1_18_, &KinematicsSolver::calc_Mxi_1_19_, &KinematicsSolver::calc_Mxi_1_20_, &KinematicsSolver::calc_Mxi_1_21_, &KinematicsSolver::calc_Mxi_1_22_, &KinematicsSolver::calc_Mxi_1_23_, &KinematicsSolver::calc_Mxi_1_24_, &KinematicsSolver::calc_Mxi_1_25_, &KinematicsSolver::calc_Mxi_1_26_, &KinematicsSolver::calc_Mxi_1_27_ },
    { &KinematicsSolver::calc_Mxi_2_1_, &KinematicsSolver::calc_Mxi_2_2_, &KinematicsSolver::calc_Mxi_2_3_, &KinematicsSolver::calc_Mxi_2_4_, &KinematicsSolver::calc_Mxi_2_5_, &KinematicsSolver::calc_Mxi_2_6_, &KinematicsSolver::calc_Mxi_2_7_, &KinematicsSolver::calc_Mxi_2_8_, &KinematicsSolver::calc_Mxi_2_9_, &KinematicsSolver::calc_Mxi_2_10_, &KinematicsSolver::calc_Mxi_2_11_, &KinematicsSolver::calc_Mxi_2_12_, &KinematicsSolver::calc_Mxi_2_13_, &KinematicsSolver::calc_Mxi_2_14_, &KinematicsSolver::calc_Mxi_2_15_, &KinematicsSolver::calc_Mxi_2_16_, &KinematicsSolver::calc_Mxi_2_17_, &KinematicsSolver::calc_Mxi_2_18_, &KinematicsSolver::calc_Mxi_2_19_, &KinematicsSolver::calc_Mxi_2_20_, &KinematicsSolver::calc_Mxi_2_21_, &KinematicsSolver::calc_Mxi_2_22_, &KinematicsSolver::calc_Mxi_2_23_, &KinematicsSolver::calc_Mxi_2_24_, &KinematicsSolver::calc_Mxi_2_25_, &KinematicsSolver::calc_Mxi_2_26_, &KinematicsSolver::calc_Mxi_2_27_ },
    { &KinematicsSolver::calc_Mxi_3_1_, &KinematicsSolver::calc_Mxi_3_2_, &KinematicsSolver::calc_Mxi_3_3_, &KinematicsSolver::calc_Mxi_3_4_, &KinematicsSolver::calc_Mxi_3_5_, &KinematicsSolver::calc_Mxi_3_6_, &KinematicsSolver::calc_Mxi_3_7_, &KinematicsSolver::calc_Mxi_3_8_, &KinematicsSolver::calc_Mxi_3_9_, &KinematicsSolver::calc_Mxi_3_10_, &KinematicsSolver::calc_Mxi_3_11_, &KinematicsSolver::calc_Mxi_3_12_, &KinematicsSolver::calc_Mxi_3_13_, &KinematicsSolver::calc_Mxi_3_14_, &KinematicsSolver::calc_Mxi_3_15_, &KinematicsSolver::calc_Mxi_3_16_, &KinematicsSolver::calc_Mxi_3_17_, &KinematicsSolver::calc_Mxi_3_18_, &KinematicsSolver::calc_Mxi_3_19_, &KinematicsSolver::calc_Mxi_3_20_, &KinematicsSolver::calc_Mxi_3_21_, &KinematicsSolver::calc_Mxi_3_22_, &KinematicsSolver::calc_Mxi_3_23_, &KinematicsSolver::calc_Mxi_3_24_, &KinematicsSolver::calc_Mxi_3_25_, &KinematicsSolver::calc_Mxi_3_26_, &KinematicsSolver::calc_Mxi_3_27_ },
    { &KinematicsSolver::calc_Mxi_4_1_, &KinematicsSolver::calc_Mxi_4_2_, &KinematicsSolver::calc_Mxi_4_3_, &KinematicsSolver::calc_Mxi_4_4_, &KinematicsSolver::calc_Mxi_4_5_, &KinematicsSolver::calc_Mxi_4_6_, &KinematicsSolver::calc_Mxi_4_7_, &KinematicsSolver::calc_Mxi_4_8_, &KinematicsSolver::calc_Mxi_4_9_, &KinematicsSolver::calc_Mxi_4_10_, &KinematicsSolver::calc_Mxi_4_11_, &KinematicsSolver::calc_Mxi_4_12_, &KinematicsSolver::calc_Mxi_4_13_, &KinematicsSolver::calc_Mxi_4_14_, &KinematicsSolver::calc_Mxi_4_15_, &KinematicsSolver::calc_Mxi_4_16_, &KinematicsSolver::calc_Mxi_4_17_, &KinematicsSolver::calc_Mxi_4_18_, &KinematicsSolver::calc_Mxi_4_19_, &KinematicsSolver::calc_Mxi_4_20_, &KinematicsSolver::calc_Mxi_4_21_, &KinematicsSolver::calc_Mxi_4_22_, &KinematicsSolver::calc_Mxi_4_23_, &KinematicsSolver::calc_Mxi_4_24_, &KinematicsSolver::calc_Mxi_4_25_, &KinematicsSolver::calc_Mxi_4_26_, &KinematicsSolver::calc_Mxi_4_27_ },
    { &KinematicsSolver::calc_Mxi_5_1_, &KinematicsSolver::calc_Mxi_5_2_, &KinematicsSolver::calc_Mxi_5_3_, &KinematicsSolver::calc_Mxi_5_4_, &KinematicsSolver::calc_Mxi_5_5_, &KinematicsSolver::calc_Mxi_5_6_, &KinematicsSolver::calc_Mxi_5_7_, &KinematicsSolver::calc_Mxi_5_8_, &KinematicsSolver::calc_Mxi_5_9_, &KinematicsSolver::calc_Mxi_5_10_, &KinematicsSolver::calc_Mxi_5_11_, &KinematicsSolver::calc_Mxi_5_12_, &KinematicsSolver::calc_Mxi_5_13_, &KinematicsSolver::calc_Mxi_5_14_, &KinematicsSolver::calc_Mxi_5_15_, &KinematicsSolver::calc_Mxi_5_16_, &KinematicsSolver::calc_Mxi_5_17_, &KinematicsSolver::calc_Mxi_5_18_, &KinematicsSolver::calc_Mxi_5_19_, &KinematicsSolver::calc_Mxi_5_20_, &KinematicsSolver::calc_Mxi_5_21_, &KinematicsSolver::calc_Mxi_5_22_, &KinematicsSolver::calc_Mxi_5_23_, &KinematicsSolver::calc_Mxi_5_24_, &KinematicsSolver::calc_Mxi_5_25_, &KinematicsSolver::calc_Mxi_5_26_, &KinematicsSolver::calc_Mxi_5_27_ },
    { &KinematicsSolver::calc_Mxi_6_1_, &KinematicsSolver::calc_Mxi_6_2_, &KinematicsSolver::calc_Mxi_6_3_, &KinematicsSolver::calc_Mxi_6_4_, &KinematicsSolver::calc_Mxi_6_5_, &KinematicsSolver::calc_Mxi_6_6_, &KinematicsSolver::calc_Mxi_6_7_, &KinematicsSolver::calc_Mxi_6_8_, &KinematicsSolver::calc_Mxi_6_9_, &KinematicsSolver::calc_Mxi_6_10_, &KinematicsSolver::calc_Mxi_6_11_, &KinematicsSolver::calc_Mxi_6_12_, &KinematicsSolver::calc_Mxi_6_13_, &KinematicsSolver::calc_Mxi_6_14_, &KinematicsSolver::calc_Mxi_6_15_, &KinematicsSolver::calc_Mxi_6_16_, &KinematicsSolver::calc_Mxi_6_17_, &KinematicsSolver::calc_Mxi_6_18_, &KinematicsSolver::calc_Mxi_6_19_, &KinematicsSolver::calc_Mxi_6_20_, &KinematicsSolver::calc_Mxi_6_21_, &KinematicsSolver::calc_Mxi_6_22_, &KinematicsSolver::calc_Mxi_6_23_, &KinematicsSolver::calc_Mxi_6_24_, &KinematicsSolver::calc_Mxi_6_25_, &KinematicsSolver::calc_Mxi_6_26_, &KinematicsSolver::calc_Mxi_6_27_ },
    { &KinematicsSolver::calc_Mxi_7_1_, &KinematicsSolver::calc_Mxi_7_2_, &KinematicsSolver::calc_Mxi_7_3_, &KinematicsSolver::calc_Mxi_7_4_, &KinematicsSolver::calc_Mxi_7_5_, &KinematicsSolver::calc_Mxi_7_6_, &KinematicsSolver::calc_Mxi_7_7_, &KinematicsSolver::calc_Mxi_7_8_, &KinematicsSolver::calc_Mxi_7_9_, &KinematicsSolver::calc_Mxi_7_10_, &KinematicsSolver::calc_Mxi_7_11_, &KinematicsSolver::calc_Mxi_7_12_, &KinematicsSolver::calc_Mxi_7_13_, &KinematicsSolver::calc_Mxi_7_14_, &KinematicsSolver::calc_Mxi_7_15_, &KinematicsSolver::calc_Mxi_7_16_, &KinematicsSolver::calc_Mxi_7_17_, &KinematicsSolver::calc_Mxi_7_18_, &KinematicsSolver::calc_Mxi_7_19_, &KinematicsSolver::calc_Mxi_7_20_, &KinematicsSolver::calc_Mxi_7_21_, &KinematicsSolver::calc_Mxi_7_22_, &KinematicsSolver::calc_Mxi_7_23_, &KinematicsSolver::calc_Mxi_7_24_, &KinematicsSolver::calc_Mxi_7_25_, &KinematicsSolver::calc_Mxi_7_26_, &KinematicsSolver::calc_Mxi_7_27_ },
    { &KinematicsSolver::calc_Mxi_8_1_, &KinematicsSolver::calc_Mxi_8_2_, &KinematicsSolver::calc_Mxi_8_3_, &KinematicsSolver::calc_Mxi_8_4_, &KinematicsSolver::calc_Mxi_8_5_, &KinematicsSolver::calc_Mxi_8_6_, &KinematicsSolver::calc_Mxi_8_7_, &KinematicsSolver::calc_Mxi_8_8_, &KinematicsSolver::calc_Mxi_8_9_, &KinematicsSolver::calc_Mxi_8_10_, &KinematicsSolver::calc_Mxi_8_11_, &KinematicsSolver::calc_Mxi_8_12_, &KinematicsSolver::calc_Mxi_8_13_, &KinematicsSolver::calc_Mxi_8_14_, &KinematicsSolver::calc_Mxi_8_15_, &KinematicsSolver::calc_Mxi_8_16_, &KinematicsSolver::calc_Mxi_8_17_, &KinematicsSolver::calc_Mxi_8_18_, &KinematicsSolver::calc_Mxi_8_19_, &KinematicsSolver::calc_Mxi_8_20_, &KinematicsSolver::calc_Mxi_8_21_, &KinematicsSolver::calc_Mxi_8_22_, &KinematicsSolver::calc_Mxi_8_23_, &KinematicsSolver::calc_Mxi_8_24_, &KinematicsSolver::calc_Mxi_8_25_, &KinematicsSolver::calc_Mxi_8_26_, &KinematicsSolver::calc_Mxi_8_27_ },
    { &KinematicsSolver::calc_Mxi_9_1_, &KinematicsSolver::calc_Mxi_9_2_, &KinematicsSolver::calc_Mxi_9_3_, &KinematicsSolver::calc_Mxi_9_4_, &KinematicsSolver::calc_Mxi_9_5_, &KinematicsSolver::calc_Mxi_9_6_, &KinematicsSolver::calc_Mxi_9_7_, &KinematicsSolver::calc_Mxi_9_8_, &KinematicsSolver::calc_Mxi_9_9_, &KinematicsSolver::calc_Mxi_9_10_, &KinematicsSolver::calc_Mxi_9_11_, &KinematicsSolver::calc_Mxi_9_12_, &KinematicsSolver::calc_Mxi_9_13_, &KinematicsSolver::calc_Mxi_9_14_, &KinematicsSolver::calc_Mxi_9_15_, &KinematicsSolver::calc_Mxi_9_16_, &KinematicsSolver::calc_Mxi_9_17_, &KinematicsSolver::calc_Mxi_9_18_, &KinematicsSolver::calc_Mxi_9_19_, &KinematicsSolver::calc_Mxi_9_20_, &KinematicsSolver::calc_Mxi_9_21_, &KinematicsSolver::calc_Mxi_9_22_, &KinematicsSolver::calc_Mxi_9_23_, &KinematicsSolver::calc_Mxi_9_24_, &KinematicsSolver::calc_Mxi_9_25_, &KinematicsSolver::calc_Mxi_9_26_, &KinematicsSolver::calc_Mxi_9_27_ },
    { &KinematicsSolver::calc_Mxi_10_1_, &KinematicsSolver::calc_Mxi_10_2_, &KinematicsSolver::calc_Mxi_10_3_, &KinematicsSolver::calc_Mxi_10_4_, &KinematicsSolver::calc_Mxi_10_5_, &KinematicsSolver::calc_Mxi_10_6_, &KinematicsSolver::calc_Mxi_10_7_, &KinematicsSolver::calc_Mxi_10_8_, &KinematicsSolver::calc_Mxi_10_9_, &KinematicsSolver::calc_Mxi_10_10_, &KinematicsSolver::calc_Mxi_10_11_, &KinematicsSolver::calc_Mxi_10_12_, &KinematicsSolver::calc_Mxi_10_13_, &KinematicsSolver::calc_Mxi_10_14_, &KinematicsSolver::calc_Mxi_10_15_, &KinematicsSolver::calc_Mxi_10_16_, &KinematicsSolver::calc_Mxi_10_17_, &KinematicsSolver::calc_Mxi_10_18_, &KinematicsSolver::calc_Mxi_10_19_, &KinematicsSolver::calc_Mxi_10_20_, &KinematicsSolver::calc_Mxi_10_21_, &KinematicsSolver::calc_Mxi_10_22_, &KinematicsSolver::calc_Mxi_10_23_, &KinematicsSolver::calc_Mxi_10_24_, &KinematicsSolver::calc_Mxi_10_25_, &KinematicsSolver::calc_Mxi_10_26_, &KinematicsSolver::calc_Mxi_10_27_ },
    { &KinematicsSolver::calc_Mxi_11_1_, &KinematicsSolver::calc_Mxi_11_2_, &KinematicsSolver::calc_Mxi_11_3_, &KinematicsSolver::calc_Mxi_11_4_, &KinematicsSolver::calc_Mxi_11_5_, &KinematicsSolver::calc_Mxi_11_6_, &KinematicsSolver::calc_Mxi_11_7_, &KinematicsSolver::calc_Mxi_11_8_, &KinematicsSolver::calc_Mxi_11_9_, &KinematicsSolver::calc_Mxi_11_10_, &KinematicsSolver::calc_Mxi_11_11_, &KinematicsSolver::calc_Mxi_11_12_, &KinematicsSolver::calc_Mxi_11_13_, &KinematicsSolver::calc_Mxi_11_14_, &KinematicsSolver::calc_Mxi_11_15_, &KinematicsSolver::calc_Mxi_11_16_, &KinematicsSolver::calc_Mxi_11_17_, &KinematicsSolver::calc_Mxi_11_18_, &KinematicsSolver::calc_Mxi_11_19_, &KinematicsSolver::calc_Mxi_11_20_, &KinematicsSolver::calc_Mxi_11_21_, &KinematicsSolver::calc_Mxi_11_22_, &KinematicsSolver::calc_Mxi_11_23_, &KinematicsSolver::calc_Mxi_11_24_, &KinematicsSolver::calc_Mxi_11_25_, &KinematicsSolver::calc_Mxi_11_26_, &KinematicsSolver::calc_Mxi_11_27_ },
    { &KinematicsSolver::calc_Mxi_12_1_, &KinematicsSolver::calc_Mxi_12_2_, &KinematicsSolver::calc_Mxi_12_3_, &KinematicsSolver::calc_Mxi_12_4_, &KinematicsSolver::calc_Mxi_12_5_, &KinematicsSolver::calc_Mxi_12_6_, &KinematicsSolver::calc_Mxi_12_7_, &KinematicsSolver::calc_Mxi_12_8_, &KinematicsSolver::calc_Mxi_12_9_, &KinematicsSolver::calc_Mxi_12_10_, &KinematicsSolver::calc_Mxi_12_11_, &KinematicsSolver::calc_Mxi_12_12_, &KinematicsSolver::calc_Mxi_12_13_, &KinematicsSolver::calc_Mxi_12_14_, &KinematicsSolver::calc_Mxi_12_15_, &KinematicsSolver::calc_Mxi_12_16_, &KinematicsSolver::calc_Mxi_12_17_, &KinematicsSolver::calc_Mxi_12_18_, &KinematicsSolver::calc_Mxi_12_19_, &KinematicsSolver::calc_Mxi_12_20_, &KinematicsSolver::calc_Mxi_12_21_, &KinematicsSolver::calc_Mxi_12_22_, &KinematicsSolver::calc_Mxi_12_23_, &KinematicsSolver::calc_Mxi_12_24_, &KinematicsSolver::calc_Mxi_12_25_, &KinematicsSolver::calc_Mxi_12_26_, &KinematicsSolver::calc_Mxi_12_27_ },
    { &KinematicsSolver::calc_Mxi_13_1_, &KinematicsSolver::calc_Mxi_13_2_, &KinematicsSolver::calc_Mxi_13_3_, &KinematicsSolver::calc_Mxi_13_4_, &KinematicsSolver::calc_Mxi_13_5_, &KinematicsSolver::calc_Mxi_13_6_, &KinematicsSolver::calc_Mxi_13_7_, &KinematicsSolver::calc_Mxi_13_8_, &KinematicsSolver::calc_Mxi_13_9_, &KinematicsSolver::calc_Mxi_13_10_, &KinematicsSolver::calc_Mxi_13_11_, &KinematicsSolver::calc_Mxi_13_12_, &KinematicsSolver::calc_Mxi_13_13_, &KinematicsSolver::calc_Mxi_13_14_, &KinematicsSolver::calc_Mxi_13_15_, &KinematicsSolver::calc_Mxi_13_16_, &KinematicsSolver::calc_Mxi_13_17_, &KinematicsSolver::calc_Mxi_13_18_, &KinematicsSolver::calc_Mxi_13_19_, &KinematicsSolver::calc_Mxi_13_20_, &KinematicsSolver::calc_Mxi_13_21_, &KinematicsSolver::calc_Mxi_13_22_, &KinematicsSolver::calc_Mxi_13_23_, &KinematicsSolver::calc_Mxi_13_24_, &KinematicsSolver::calc_Mxi_13_25_, &KinematicsSolver::calc_Mxi_13_26_, &KinematicsSolver::calc_Mxi_13_27_ },
    { &KinematicsSolver::calc_Mxi_14_1_, &KinematicsSolver::calc_Mxi_14_2_, &KinematicsSolver::calc_Mxi_14_3_, &KinematicsSolver::calc_Mxi_14_4_, &KinematicsSolver::calc_Mxi_14_5_, &KinematicsSolver::calc_Mxi_14_6_, &KinematicsSolver::calc_Mxi_14_7_, &KinematicsSolver::calc_Mxi_14_8_, &KinematicsSolver::calc_Mxi_14_9_, &KinematicsSolver::calc_Mxi_14_10_, &KinematicsSolver::calc_Mxi_14_11_, &KinematicsSolver::calc_Mxi_14_12_, &KinematicsSolver::calc_Mxi_14_13_, &KinematicsSolver::calc_Mxi_14_14_, &KinematicsSolver::calc_Mxi_14_15_, &KinematicsSolver::calc_Mxi_14_16_, &KinematicsSolver::calc_Mxi_14_17_, &KinematicsSolver::calc_Mxi_14_18_, &KinematicsSolver::calc_Mxi_14_19_, &KinematicsSolver::calc_Mxi_14_20_, &KinematicsSolver::calc_Mxi_14_21_, &KinematicsSolver::calc_Mxi_14_22_, &KinematicsSolver::calc_Mxi_14_23_, &KinematicsSolver::calc_Mxi_14_24_, &KinematicsSolver::calc_Mxi_14_25_, &KinematicsSolver::calc_Mxi_14_26_, &KinematicsSolver::calc_Mxi_14_27_ },
    { &KinematicsSolver::calc_Mxi_15_1_, &KinematicsSolver::calc_Mxi_15_2_, &KinematicsSolver::calc_Mxi_15_3_, &KinematicsSolver::calc_Mxi_15_4_, &KinematicsSolver::calc_Mxi_15_5_, &KinematicsSolver::calc_Mxi_15_6_, &KinematicsSolver::calc_Mxi_15_7_, &KinematicsSolver::calc_Mxi_15_8_, &KinematicsSolver::calc_Mxi_15_9_, &KinematicsSolver::calc_Mxi_15_10_, &KinematicsSolver::calc_Mxi_15_11_, &KinematicsSolver::calc_Mxi_15_12_, &KinematicsSolver::calc_Mxi_15_13_, &KinematicsSolver::calc_Mxi_15_14_, &KinematicsSolver::calc_Mxi_15_15_, &KinematicsSolver::calc_Mxi_15_16_, &KinematicsSolver::calc_Mxi_15_17_, &KinematicsSolver::calc_Mxi_15_18_, &KinematicsSolver::calc_Mxi_15_19_, &KinematicsSolver::calc_Mxi_15_20_, &KinematicsSolver::calc_Mxi_15_21_, &KinematicsSolver::calc_Mxi_15_22_, &KinematicsSolver::calc_Mxi_15_23_, &KinematicsSolver::calc_Mxi_15_24_, &KinematicsSolver::calc_Mxi_15_25_, &KinematicsSolver::calc_Mxi_15_26_, &KinematicsSolver::calc_Mxi_15_27_ },
    { &KinematicsSolver::calc_Mxi_16_1_, &KinematicsSolver::calc_Mxi_16_2_, &KinematicsSolver::calc_Mxi_16_3_, &KinematicsSolver::calc_Mxi_16_4_, &KinematicsSolver::calc_Mxi_16_5_, &KinematicsSolver::calc_Mxi_16_6_, &KinematicsSolver::calc_Mxi_16_7_, &KinematicsSolver::calc_Mxi_16_8_, &KinematicsSolver::calc_Mxi_16_9_, &KinematicsSolver::calc_Mxi_16_10_, &KinematicsSolver::calc_Mxi_16_11_, &KinematicsSolver::calc_Mxi_16_12_, &KinematicsSolver::calc_Mxi_16_13_, &KinematicsSolver::calc_Mxi_16_14_, &KinematicsSolver::calc_Mxi_16_15_, &KinematicsSolver::calc_Mxi_16_16_, &KinematicsSolver::calc_Mxi_16_17_, &KinematicsSolver::calc_Mxi_16_18_, &KinematicsSolver::calc_Mxi_16_19_, &KinematicsSolver::calc_Mxi_16_20_, &KinematicsSolver::calc_Mxi_16_21_, &KinematicsSolver::calc_Mxi_16_22_, &KinematicsSolver::calc_Mxi_16_23_, &KinematicsSolver::calc_Mxi_16_24_, &KinematicsSolver::calc_Mxi_16_25_, &KinematicsSolver::calc_Mxi_16_26_, &KinematicsSolver::calc_Mxi_16_27_ },
    { &KinematicsSolver::calc_Mxi_17_1_, &KinematicsSolver::calc_Mxi_17_2_, &KinematicsSolver::calc_Mxi_17_3_, &KinematicsSolver::calc_Mxi_17_4_, &KinematicsSolver::calc_Mxi_17_5_, &KinematicsSolver::calc_Mxi_17_6_, &KinematicsSolver::calc_Mxi_17_7_, &KinematicsSolver::calc_Mxi_17_8_, &KinematicsSolver::calc_Mxi_17_9_, &KinematicsSolver::calc_Mxi_17_10_, &KinematicsSolver::calc_Mxi_17_11_, &KinematicsSolver::calc_Mxi_17_12_, &KinematicsSolver::calc_Mxi_17_13_, &KinematicsSolver::calc_Mxi_17_14_, &KinematicsSolver::calc_Mxi_17_15_, &KinematicsSolver::calc_Mxi_17_16_, &KinematicsSolver::calc_Mxi_17_17_, &KinematicsSolver::calc_Mxi_17_18_, &KinematicsSolver::calc_Mxi_17_19_, &KinematicsSolver::calc_Mxi_17_20_, &KinematicsSolver::calc_Mxi_17_21_, &KinematicsSolver::calc_Mxi_17_22_, &KinematicsSolver::calc_Mxi_17_23_, &KinematicsSolver::calc_Mxi_17_24_, &KinematicsSolver::calc_Mxi_17_25_, &KinematicsSolver::calc_Mxi_17_26_, &KinematicsSolver::calc_Mxi_17_27_ },
    { &KinematicsSolver::calc_Mxi_18_1_, &KinematicsSolver::calc_Mxi_18_2_, &KinematicsSolver::calc_Mxi_18_3_, &KinematicsSolver::calc_Mxi_18_4_, &KinematicsSolver::calc_Mxi_18_5_, &KinematicsSolver::calc_Mxi_18_6_, &KinematicsSolver::calc_Mxi_18_7_, &KinematicsSolver::calc_Mxi_18_8_, &KinematicsSolver::calc_Mxi_18_9_, &KinematicsSolver::calc_Mxi_18_10_, &KinematicsSolver::calc_Mxi_18_11_, &KinematicsSolver::calc_Mxi_18_12_, &KinematicsSolver::calc_Mxi_18_13_, &KinematicsSolver::calc_Mxi_18_14_, &KinematicsSolver::calc_Mxi_18_15_, &KinematicsSolver::calc_Mxi_18_16_, &KinematicsSolver::calc_Mxi_18_17_, &KinematicsSolver::calc_Mxi_18_18_, &KinematicsSolver::calc_Mxi_18_19_, &KinematicsSolver::calc_Mxi_18_20_, &KinematicsSolver::calc_Mxi_18_21_, &KinematicsSolver::calc_Mxi_18_22_, &KinematicsSolver::calc_Mxi_18_23_, &KinematicsSolver::calc_Mxi_18_24_, &KinematicsSolver::calc_Mxi_18_25_, &KinematicsSolver::calc_Mxi_18_26_, &KinematicsSolver::calc_Mxi_18_27_ },
    { &KinematicsSolver::calc_Mxi_19_1_, &KinematicsSolver::calc_Mxi_19_2_, &KinematicsSolver::calc_Mxi_19_3_, &KinematicsSolver::calc_Mxi_19_4_, &KinematicsSolver::calc_Mxi_19_5_, &KinematicsSolver::calc_Mxi_19_6_, &KinematicsSolver::calc_Mxi_19_7_, &KinematicsSolver::calc_Mxi_19_8_, &KinematicsSolver::calc_Mxi_19_9_, &KinematicsSolver::calc_Mxi_19_10_, &KinematicsSolver::calc_Mxi_19_11_, &KinematicsSolver::calc_Mxi_19_12_, &KinematicsSolver::calc_Mxi_19_13_, &KinematicsSolver::calc_Mxi_19_14_, &KinematicsSolver::calc_Mxi_19_15_, &KinematicsSolver::calc_Mxi_19_16_, &KinematicsSolver::calc_Mxi_19_17_, &KinematicsSolver::calc_Mxi_19_18_, &KinematicsSolver::calc_Mxi_19_19_, &KinematicsSolver::calc_Mxi_19_20_, &KinematicsSolver::calc_Mxi_19_21_, &KinematicsSolver::calc_Mxi_19_22_, &KinematicsSolver::calc_Mxi_19_23_, &KinematicsSolver::calc_Mxi_19_24_, &KinematicsSolver::calc_Mxi_19_25_, &KinematicsSolver::calc_Mxi_19_26_, &KinematicsSolver::calc_Mxi_19_27_ },
    { &KinematicsSolver::calc_Mxi_20_1_, &KinematicsSolver::calc_Mxi_20_2_, &KinematicsSolver::calc_Mxi_20_3_, &KinematicsSolver::calc_Mxi_20_4_, &KinematicsSolver::calc_Mxi_20_5_, &KinematicsSolver::calc_Mxi_20_6_, &KinematicsSolver::calc_Mxi_20_7_, &KinematicsSolver::calc_Mxi_20_8_, &KinematicsSolver::calc_Mxi_20_9_, &KinematicsSolver::calc_Mxi_20_10_, &KinematicsSolver::calc_Mxi_20_11_, &KinematicsSolver::calc_Mxi_20_12_, &KinematicsSolver::calc_Mxi_20_13_, &KinematicsSolver::calc_Mxi_20_14_, &KinematicsSolver::calc_Mxi_20_15_, &KinematicsSolver::calc_Mxi_20_16_, &KinematicsSolver::calc_Mxi_20_17_, &KinematicsSolver::calc_Mxi_20_18_, &KinematicsSolver::calc_Mxi_20_19_, &KinematicsSolver::calc_Mxi_20_20_, &KinematicsSolver::calc_Mxi_20_21_, &KinematicsSolver::calc_Mxi_20_22_, &KinematicsSolver::calc_Mxi_20_23_, &KinematicsSolver::calc_Mxi_20_24_, &KinematicsSolver::calc_Mxi_20_25_, &KinematicsSolver::calc_Mxi_20_26_, &KinematicsSolver::calc_Mxi_20_27_ },
    { &KinematicsSolver::calc_Mxi_21_1_, &KinematicsSolver::calc_Mxi_21_2_, &KinematicsSolver::calc_Mxi_21_3_, &KinematicsSolver::calc_Mxi_21_4_, &KinematicsSolver::calc_Mxi_21_5_, &KinematicsSolver::calc_Mxi_21_6_, &KinematicsSolver::calc_Mxi_21_7_, &KinematicsSolver::calc_Mxi_21_8_, &KinematicsSolver::calc_Mxi_21_9_, &KinematicsSolver::calc_Mxi_21_10_, &KinematicsSolver::calc_Mxi_21_11_, &KinematicsSolver::calc_Mxi_21_12_, &KinematicsSolver::calc_Mxi_21_13_, &KinematicsSolver::calc_Mxi_21_14_, &KinematicsSolver::calc_Mxi_21_15_, &KinematicsSolver::calc_Mxi_21_16_, &KinematicsSolver::calc_Mxi_21_17_, &KinematicsSolver::calc_Mxi_21_18_, &KinematicsSolver::calc_Mxi_21_19_, &KinematicsSolver::calc_Mxi_21_20_, &KinematicsSolver::calc_Mxi_21_21_, &KinematicsSolver::calc_Mxi_21_22_, &KinematicsSolver::calc_Mxi_21_23_, &KinematicsSolver::calc_Mxi_21_24_, &KinematicsSolver::calc_Mxi_21_25_, &KinematicsSolver::calc_Mxi_21_26_, &KinematicsSolver::calc_Mxi_21_27_ },
    { &KinematicsSolver::calc_Mxi_22_1_, &KinematicsSolver::calc_Mxi_22_2_, &KinematicsSolver::calc_Mxi_22_3_, &KinematicsSolver::calc_Mxi_22_4_, &KinematicsSolver::calc_Mxi_22_5_, &KinematicsSolver::calc_Mxi_22_6_, &KinematicsSolver::calc_Mxi_22_7_, &KinematicsSolver::calc_Mxi_22_8_, &KinematicsSolver::calc_Mxi_22_9_, &KinematicsSolver::calc_Mxi_22_10_, &KinematicsSolver::calc_Mxi_22_11_, &KinematicsSolver::calc_Mxi_22_12_, &KinematicsSolver::calc_Mxi_22_13_, &KinematicsSolver::calc_Mxi_22_14_, &KinematicsSolver::calc_Mxi_22_15_, &KinematicsSolver::calc_Mxi_22_16_, &KinematicsSolver::calc_Mxi_22_17_, &KinematicsSolver::calc_Mxi_22_18_, &KinematicsSolver::calc_Mxi_22_19_, &KinematicsSolver::calc_Mxi_22_20_, &KinematicsSolver::calc_Mxi_22_21_, &KinematicsSolver::calc_Mxi_22_22_, &KinematicsSolver::calc_Mxi_22_23_, &KinematicsSolver::calc_Mxi_22_24_, &KinematicsSolver::calc_Mxi_22_25_, &KinematicsSolver::calc_Mxi_22_26_, &KinematicsSolver::calc_Mxi_22_27_ },
    { &KinematicsSolver::calc_Mxi_23_1_, &KinematicsSolver::calc_Mxi_23_2_, &KinematicsSolver::calc_Mxi_23_3_, &KinematicsSolver::calc_Mxi_23_4_, &KinematicsSolver::calc_Mxi_23_5_, &KinematicsSolver::calc_Mxi_23_6_, &KinematicsSolver::calc_Mxi_23_7_, &KinematicsSolver::calc_Mxi_23_8_, &KinematicsSolver::calc_Mxi_23_9_, &KinematicsSolver::calc_Mxi_23_10_, &KinematicsSolver::calc_Mxi_23_11_, &KinematicsSolver::calc_Mxi_23_12_, &KinematicsSolver::calc_Mxi_23_13_, &KinematicsSolver::calc_Mxi_23_14_, &KinematicsSolver::calc_Mxi_23_15_, &KinematicsSolver::calc_Mxi_23_16_, &KinematicsSolver::calc_Mxi_23_17_, &KinematicsSolver::calc_Mxi_23_18_, &KinematicsSolver::calc_Mxi_23_19_, &KinematicsSolver::calc_Mxi_23_20_, &KinematicsSolver::calc_Mxi_23_21_, &KinematicsSolver::calc_Mxi_23_22_, &KinematicsSolver::calc_Mxi_23_23_, &KinematicsSolver::calc_Mxi_23_24_, &KinematicsSolver::calc_Mxi_23_25_, &KinematicsSolver::calc_Mxi_23_26_, &KinematicsSolver::calc_Mxi_23_27_ },
    { &KinematicsSolver::calc_Mxi_24_1_, &KinematicsSolver::calc_Mxi_24_2_, &KinematicsSolver::calc_Mxi_24_3_, &KinematicsSolver::calc_Mxi_24_4_, &KinematicsSolver::calc_Mxi_24_5_, &KinematicsSolver::calc_Mxi_24_6_, &KinematicsSolver::calc_Mxi_24_7_, &KinematicsSolver::calc_Mxi_24_8_, &KinematicsSolver::calc_Mxi_24_9_, &KinematicsSolver::calc_Mxi_24_10_, &KinematicsSolver::calc_Mxi_24_11_, &KinematicsSolver::calc_Mxi_24_12_, &KinematicsSolver::calc_Mxi_24_13_, &KinematicsSolver::calc_Mxi_24_14_, &KinematicsSolver::calc_Mxi_24_15_, &KinematicsSolver::calc_Mxi_24_16_, &KinematicsSolver::calc_Mxi_24_17_, &KinematicsSolver::calc_Mxi_24_18_, &KinematicsSolver::calc_Mxi_24_19_, &KinematicsSolver::calc_Mxi_24_20_, &KinematicsSolver::calc_Mxi_24_21_, &KinematicsSolver::calc_Mxi_24_22_, &KinematicsSolver::calc_Mxi_24_23_, &KinematicsSolver::calc_Mxi_24_24_, &KinematicsSolver::calc_Mxi_24_25_, &KinematicsSolver::calc_Mxi_24_26_, &KinematicsSolver::calc_Mxi_24_27_ },
    { &KinematicsSolver::calc_Mxi_25_1_, &KinematicsSolver::calc_Mxi_25_2_, &KinematicsSolver::calc_Mxi_25_3_, &KinematicsSolver::calc_Mxi_25_4_, &KinematicsSolver::calc_Mxi_25_5_, &KinematicsSolver::calc_Mxi_25_6_, &KinematicsSolver::calc_Mxi_25_7_, &KinematicsSolver::calc_Mxi_25_8_, &KinematicsSolver::calc_Mxi_25_9_, &KinematicsSolver::calc_Mxi_25_10_, &KinematicsSolver::calc_Mxi_25_11_, &KinematicsSolver::calc_Mxi_25_12_, &KinematicsSolver::calc_Mxi_25_13_, &KinematicsSolver::calc_Mxi_25_14_, &KinematicsSolver::calc_Mxi_25_15_, &KinematicsSolver::calc_Mxi_25_16_, &KinematicsSolver::calc_Mxi_25_17_, &KinematicsSolver::calc_Mxi_25_18_, &KinematicsSolver::calc_Mxi_25_19_, &KinematicsSolver::calc_Mxi_25_20_, &KinematicsSolver::calc_Mxi_25_21_, &KinematicsSolver::calc_Mxi_25_22_, &KinematicsSolver::calc_Mxi_25_23_, &KinematicsSolver::calc_Mxi_25_24_, &KinematicsSolver::calc_Mxi_25_25_, &KinematicsSolver::calc_Mxi_25_26_, &KinematicsSolver::calc_Mxi_25_27_ },
    { &KinematicsSolver::calc_Mxi_26_1_, &KinematicsSolver::calc_Mxi_26_2_, &KinematicsSolver::calc_Mxi_26_3_, &KinematicsSolver::calc_Mxi_26_4_, &KinematicsSolver::calc_Mxi_26_5_, &KinematicsSolver::calc_Mxi_26_6_, &KinematicsSolver::calc_Mxi_26_7_, &KinematicsSolver::calc_Mxi_26_8_, &KinematicsSolver::calc_Mxi_26_9_, &KinematicsSolver::calc_Mxi_26_10_, &KinematicsSolver::calc_Mxi_26_11_, &KinematicsSolver::calc_Mxi_26_12_, &KinematicsSolver::calc_Mxi_26_13_, &KinematicsSolver::calc_Mxi_26_14_, &KinematicsSolver::calc_Mxi_26_15_, &KinematicsSolver::calc_Mxi_26_16_, &KinematicsSolver::calc_Mxi_26_17_, &KinematicsSolver::calc_Mxi_26_18_, &KinematicsSolver::calc_Mxi_26_19_, &KinematicsSolver::calc_Mxi_26_20_, &KinematicsSolver::calc_Mxi_26_21_, &KinematicsSolver::calc_Mxi_26_22_, &KinematicsSolver::calc_Mxi_26_23_, &KinematicsSolver::calc_Mxi_26_24_, &KinematicsSolver::calc_Mxi_26_25_, &KinematicsSolver::calc_Mxi_26_26_, &KinematicsSolver::calc_Mxi_26_27_ },
    { &KinematicsSolver::calc_Mxi_27_1_, &KinematicsSolver::calc_Mxi_27_2_, &KinematicsSolver::calc_Mxi_27_3_, &KinematicsSolver::calc_Mxi_27_4_, &KinematicsSolver::calc_Mxi_27_5_, &KinematicsSolver::calc_Mxi_27_6_, &KinematicsSolver::calc_Mxi_27_7_, &KinematicsSolver::calc_Mxi_27_8_, &KinematicsSolver::calc_Mxi_27_9_, &KinematicsSolver::calc_Mxi_27_10_, &KinematicsSolver::calc_Mxi_27_11_, &KinematicsSolver::calc_Mxi_27_12_, &KinematicsSolver::calc_Mxi_27_13_, &KinematicsSolver::calc_Mxi_27_14_, &KinematicsSolver::calc_Mxi_27_15_, &KinematicsSolver::calc_Mxi_27_16_, &KinematicsSolver::calc_Mxi_27_17_, &KinematicsSolver::calc_Mxi_27_18_, &KinematicsSolver::calc_Mxi_27_19_, &KinematicsSolver::calc_Mxi_27_20_, &KinematicsSolver::calc_Mxi_27_21_, &KinematicsSolver::calc_Mxi_27_22_, &KinematicsSolver::calc_Mxi_27_23_, &KinematicsSolver::calc_Mxi_27_24_, &KinematicsSolver::calc_Mxi_27_25_, &KinematicsSolver::calc_Mxi_27_26_, &KinematicsSolver::calc_Mxi_27_27_ }
  };
  
  
  // --- Axi 18x27 ---
  inline static constexpr Mfn Axi_tbl[18][27] = {
    { &KinematicsSolver::calc_Axi_1_1_, &KinematicsSolver::calc_Axi_1_2_, &KinematicsSolver::calc_Axi_1_3_, &KinematicsSolver::calc_Axi_1_4_, &KinematicsSolver::calc_Axi_1_5_, &KinematicsSolver::calc_Axi_1_6_, &KinematicsSolver::calc_Axi_1_7_, &KinematicsSolver::calc_Axi_1_8_, &KinematicsSolver::calc_Axi_1_9_, &KinematicsSolver::calc_Axi_1_10_, &KinematicsSolver::calc_Axi_1_11_, &KinematicsSolver::calc_Axi_1_12_, &KinematicsSolver::calc_Axi_1_13_, &KinematicsSolver::calc_Axi_1_14_, &KinematicsSolver::calc_Axi_1_15_, &KinematicsSolver::calc_Axi_1_16_, &KinematicsSolver::calc_Axi_1_17_, &KinematicsSolver::calc_Axi_1_18_, &KinematicsSolver::calc_Axi_1_19_, &KinematicsSolver::calc_Axi_1_20_, &KinematicsSolver::calc_Axi_1_21_, &KinematicsSolver::calc_Axi_1_22_, &KinematicsSolver::calc_Axi_1_23_, &KinematicsSolver::calc_Axi_1_24_, &KinematicsSolver::calc_Axi_1_25_, &KinematicsSolver::calc_Axi_1_26_, &KinematicsSolver::calc_Axi_1_27_ },
    { &KinematicsSolver::calc_Axi_2_1_, &KinematicsSolver::calc_Axi_2_2_, &KinematicsSolver::calc_Axi_2_3_, &KinematicsSolver::calc_Axi_2_4_, &KinematicsSolver::calc_Axi_2_5_, &KinematicsSolver::calc_Axi_2_6_, &KinematicsSolver::calc_Axi_2_7_, &KinematicsSolver::calc_Axi_2_8_, &KinematicsSolver::calc_Axi_2_9_, &KinematicsSolver::calc_Axi_2_10_, &KinematicsSolver::calc_Axi_2_11_, &KinematicsSolver::calc_Axi_2_12_, &KinematicsSolver::calc_Axi_2_13_, &KinematicsSolver::calc_Axi_2_14_, &KinematicsSolver::calc_Axi_2_15_, &KinematicsSolver::calc_Axi_2_16_, &KinematicsSolver::calc_Axi_2_17_, &KinematicsSolver::calc_Axi_2_18_, &KinematicsSolver::calc_Axi_2_19_, &KinematicsSolver::calc_Axi_2_20_, &KinematicsSolver::calc_Axi_2_21_, &KinematicsSolver::calc_Axi_2_22_, &KinematicsSolver::calc_Axi_2_23_, &KinematicsSolver::calc_Axi_2_24_, &KinematicsSolver::calc_Axi_2_25_, &KinematicsSolver::calc_Axi_2_26_, &KinematicsSolver::calc_Axi_2_27_ },
    { &KinematicsSolver::calc_Axi_3_1_, &KinematicsSolver::calc_Axi_3_2_, &KinematicsSolver::calc_Axi_3_3_, &KinematicsSolver::calc_Axi_3_4_, &KinematicsSolver::calc_Axi_3_5_, &KinematicsSolver::calc_Axi_3_6_, &KinematicsSolver::calc_Axi_3_7_, &KinematicsSolver::calc_Axi_3_8_, &KinematicsSolver::calc_Axi_3_9_, &KinematicsSolver::calc_Axi_3_10_, &KinematicsSolver::calc_Axi_3_11_, &KinematicsSolver::calc_Axi_3_12_, &KinematicsSolver::calc_Axi_3_13_, &KinematicsSolver::calc_Axi_3_14_, &KinematicsSolver::calc_Axi_3_15_, &KinematicsSolver::calc_Axi_3_16_, &KinematicsSolver::calc_Axi_3_17_, &KinematicsSolver::calc_Axi_3_18_, &KinematicsSolver::calc_Axi_3_19_, &KinematicsSolver::calc_Axi_3_20_, &KinematicsSolver::calc_Axi_3_21_, &KinematicsSolver::calc_Axi_3_22_, &KinematicsSolver::calc_Axi_3_23_, &KinematicsSolver::calc_Axi_3_24_, &KinematicsSolver::calc_Axi_3_25_, &KinematicsSolver::calc_Axi_3_26_, &KinematicsSolver::calc_Axi_3_27_ },
    { &KinematicsSolver::calc_Axi_4_1_, &KinematicsSolver::calc_Axi_4_2_, &KinematicsSolver::calc_Axi_4_3_, &KinematicsSolver::calc_Axi_4_4_, &KinematicsSolver::calc_Axi_4_5_, &KinematicsSolver::calc_Axi_4_6_, &KinematicsSolver::calc_Axi_4_7_, &KinematicsSolver::calc_Axi_4_8_, &KinematicsSolver::calc_Axi_4_9_, &KinematicsSolver::calc_Axi_4_10_, &KinematicsSolver::calc_Axi_4_11_, &KinematicsSolver::calc_Axi_4_12_, &KinematicsSolver::calc_Axi_4_13_, &KinematicsSolver::calc_Axi_4_14_, &KinematicsSolver::calc_Axi_4_15_, &KinematicsSolver::calc_Axi_4_16_, &KinematicsSolver::calc_Axi_4_17_, &KinematicsSolver::calc_Axi_4_18_, &KinematicsSolver::calc_Axi_4_19_, &KinematicsSolver::calc_Axi_4_20_, &KinematicsSolver::calc_Axi_4_21_, &KinematicsSolver::calc_Axi_4_22_, &KinematicsSolver::calc_Axi_4_23_, &KinematicsSolver::calc_Axi_4_24_, &KinematicsSolver::calc_Axi_4_25_, &KinematicsSolver::calc_Axi_4_26_, &KinematicsSolver::calc_Axi_4_27_ },
    { &KinematicsSolver::calc_Axi_5_1_, &KinematicsSolver::calc_Axi_5_2_, &KinematicsSolver::calc_Axi_5_3_, &KinematicsSolver::calc_Axi_5_4_, &KinematicsSolver::calc_Axi_5_5_, &KinematicsSolver::calc_Axi_5_6_, &KinematicsSolver::calc_Axi_5_7_, &KinematicsSolver::calc_Axi_5_8_, &KinematicsSolver::calc_Axi_5_9_, &KinematicsSolver::calc_Axi_5_10_, &KinematicsSolver::calc_Axi_5_11_, &KinematicsSolver::calc_Axi_5_12_, &KinematicsSolver::calc_Axi_5_13_, &KinematicsSolver::calc_Axi_5_14_, &KinematicsSolver::calc_Axi_5_15_, &KinematicsSolver::calc_Axi_5_16_, &KinematicsSolver::calc_Axi_5_17_, &KinematicsSolver::calc_Axi_5_18_, &KinematicsSolver::calc_Axi_5_19_, &KinematicsSolver::calc_Axi_5_20_, &KinematicsSolver::calc_Axi_5_21_, &KinematicsSolver::calc_Axi_5_22_, &KinematicsSolver::calc_Axi_5_23_, &KinematicsSolver::calc_Axi_5_24_, &KinematicsSolver::calc_Axi_5_25_, &KinematicsSolver::calc_Axi_5_26_, &KinematicsSolver::calc_Axi_5_27_ },
    { &KinematicsSolver::calc_Axi_6_1_, &KinematicsSolver::calc_Axi_6_2_, &KinematicsSolver::calc_Axi_6_3_, &KinematicsSolver::calc_Axi_6_4_, &KinematicsSolver::calc_Axi_6_5_, &KinematicsSolver::calc_Axi_6_6_, &KinematicsSolver::calc_Axi_6_7_, &KinematicsSolver::calc_Axi_6_8_, &KinematicsSolver::calc_Axi_6_9_, &KinematicsSolver::calc_Axi_6_10_, &KinematicsSolver::calc_Axi_6_11_, &KinematicsSolver::calc_Axi_6_12_, &KinematicsSolver::calc_Axi_6_13_, &KinematicsSolver::calc_Axi_6_14_, &KinematicsSolver::calc_Axi_6_15_, &KinematicsSolver::calc_Axi_6_16_, &KinematicsSolver::calc_Axi_6_17_, &KinematicsSolver::calc_Axi_6_18_, &KinematicsSolver::calc_Axi_6_19_, &KinematicsSolver::calc_Axi_6_20_, &KinematicsSolver::calc_Axi_6_21_, &KinematicsSolver::calc_Axi_6_22_, &KinematicsSolver::calc_Axi_6_23_, &KinematicsSolver::calc_Axi_6_24_, &KinematicsSolver::calc_Axi_6_25_, &KinematicsSolver::calc_Axi_6_26_, &KinematicsSolver::calc_Axi_6_27_ },
    { &KinematicsSolver::calc_Axi_7_1_, &KinematicsSolver::calc_Axi_7_2_, &KinematicsSolver::calc_Axi_7_3_, &KinematicsSolver::calc_Axi_7_4_, &KinematicsSolver::calc_Axi_7_5_, &KinematicsSolver::calc_Axi_7_6_, &KinematicsSolver::calc_Axi_7_7_, &KinematicsSolver::calc_Axi_7_8_, &KinematicsSolver::calc_Axi_7_9_, &KinematicsSolver::calc_Axi_7_10_, &KinematicsSolver::calc_Axi_7_11_, &KinematicsSolver::calc_Axi_7_12_, &KinematicsSolver::calc_Axi_7_13_, &KinematicsSolver::calc_Axi_7_14_, &KinematicsSolver::calc_Axi_7_15_, &KinematicsSolver::calc_Axi_7_16_, &KinematicsSolver::calc_Axi_7_17_, &KinematicsSolver::calc_Axi_7_18_, &KinematicsSolver::calc_Axi_7_19_, &KinematicsSolver::calc_Axi_7_20_, &KinematicsSolver::calc_Axi_7_21_, &KinematicsSolver::calc_Axi_7_22_, &KinematicsSolver::calc_Axi_7_23_, &KinematicsSolver::calc_Axi_7_24_, &KinematicsSolver::calc_Axi_7_25_, &KinematicsSolver::calc_Axi_7_26_, &KinematicsSolver::calc_Axi_7_27_ },
    { &KinematicsSolver::calc_Axi_8_1_, &KinematicsSolver::calc_Axi_8_2_, &KinematicsSolver::calc_Axi_8_3_, &KinematicsSolver::calc_Axi_8_4_, &KinematicsSolver::calc_Axi_8_5_, &KinematicsSolver::calc_Axi_8_6_, &KinematicsSolver::calc_Axi_8_7_, &KinematicsSolver::calc_Axi_8_8_, &KinematicsSolver::calc_Axi_8_9_, &KinematicsSolver::calc_Axi_8_10_, &KinematicsSolver::calc_Axi_8_11_, &KinematicsSolver::calc_Axi_8_12_, &KinematicsSolver::calc_Axi_8_13_, &KinematicsSolver::calc_Axi_8_14_, &KinematicsSolver::calc_Axi_8_15_, &KinematicsSolver::calc_Axi_8_16_, &KinematicsSolver::calc_Axi_8_17_, &KinematicsSolver::calc_Axi_8_18_, &KinematicsSolver::calc_Axi_8_19_, &KinematicsSolver::calc_Axi_8_20_, &KinematicsSolver::calc_Axi_8_21_, &KinematicsSolver::calc_Axi_8_22_, &KinematicsSolver::calc_Axi_8_23_, &KinematicsSolver::calc_Axi_8_24_, &KinematicsSolver::calc_Axi_8_25_, &KinematicsSolver::calc_Axi_8_26_, &KinematicsSolver::calc_Axi_8_27_ },
    { &KinematicsSolver::calc_Axi_9_1_, &KinematicsSolver::calc_Axi_9_2_, &KinematicsSolver::calc_Axi_9_3_, &KinematicsSolver::calc_Axi_9_4_, &KinematicsSolver::calc_Axi_9_5_, &KinematicsSolver::calc_Axi_9_6_, &KinematicsSolver::calc_Axi_9_7_, &KinematicsSolver::calc_Axi_9_8_, &KinematicsSolver::calc_Axi_9_9_, &KinematicsSolver::calc_Axi_9_10_, &KinematicsSolver::calc_Axi_9_11_, &KinematicsSolver::calc_Axi_9_12_, &KinematicsSolver::calc_Axi_9_13_, &KinematicsSolver::calc_Axi_9_14_, &KinematicsSolver::calc_Axi_9_15_, &KinematicsSolver::calc_Axi_9_16_, &KinematicsSolver::calc_Axi_9_17_, &KinematicsSolver::calc_Axi_9_18_, &KinematicsSolver::calc_Axi_9_19_, &KinematicsSolver::calc_Axi_9_20_, &KinematicsSolver::calc_Axi_9_21_, &KinematicsSolver::calc_Axi_9_22_, &KinematicsSolver::calc_Axi_9_23_, &KinematicsSolver::calc_Axi_9_24_, &KinematicsSolver::calc_Axi_9_25_, &KinematicsSolver::calc_Axi_9_26_, &KinematicsSolver::calc_Axi_9_27_ },
    { &KinematicsSolver::calc_Axi_10_1_, &KinematicsSolver::calc_Axi_10_2_, &KinematicsSolver::calc_Axi_10_3_, &KinematicsSolver::calc_Axi_10_4_, &KinematicsSolver::calc_Axi_10_5_, &KinematicsSolver::calc_Axi_10_6_, &KinematicsSolver::calc_Axi_10_7_, &KinematicsSolver::calc_Axi_10_8_, &KinematicsSolver::calc_Axi_10_9_, &KinematicsSolver::calc_Axi_10_10_, &KinematicsSolver::calc_Axi_10_11_, &KinematicsSolver::calc_Axi_10_12_, &KinematicsSolver::calc_Axi_10_13_, &KinematicsSolver::calc_Axi_10_14_, &KinematicsSolver::calc_Axi_10_15_, &KinematicsSolver::calc_Axi_10_16_, &KinematicsSolver::calc_Axi_10_17_, &KinematicsSolver::calc_Axi_10_18_, &KinematicsSolver::calc_Axi_10_19_, &KinematicsSolver::calc_Axi_10_20_, &KinematicsSolver::calc_Axi_10_21_, &KinematicsSolver::calc_Axi_10_22_, &KinematicsSolver::calc_Axi_10_23_, &KinematicsSolver::calc_Axi_10_24_, &KinematicsSolver::calc_Axi_10_25_, &KinematicsSolver::calc_Axi_10_26_, &KinematicsSolver::calc_Axi_10_27_ },
    { &KinematicsSolver::calc_Axi_11_1_, &KinematicsSolver::calc_Axi_11_2_, &KinematicsSolver::calc_Axi_11_3_, &KinematicsSolver::calc_Axi_11_4_, &KinematicsSolver::calc_Axi_11_5_, &KinematicsSolver::calc_Axi_11_6_, &KinematicsSolver::calc_Axi_11_7_, &KinematicsSolver::calc_Axi_11_8_, &KinematicsSolver::calc_Axi_11_9_, &KinematicsSolver::calc_Axi_11_10_, &KinematicsSolver::calc_Axi_11_11_, &KinematicsSolver::calc_Axi_11_12_, &KinematicsSolver::calc_Axi_11_13_, &KinematicsSolver::calc_Axi_11_14_, &KinematicsSolver::calc_Axi_11_15_, &KinematicsSolver::calc_Axi_11_16_, &KinematicsSolver::calc_Axi_11_17_, &KinematicsSolver::calc_Axi_11_18_, &KinematicsSolver::calc_Axi_11_19_, &KinematicsSolver::calc_Axi_11_20_, &KinematicsSolver::calc_Axi_11_21_, &KinematicsSolver::calc_Axi_11_22_, &KinematicsSolver::calc_Axi_11_23_, &KinematicsSolver::calc_Axi_11_24_, &KinematicsSolver::calc_Axi_11_25_, &KinematicsSolver::calc_Axi_11_26_, &KinematicsSolver::calc_Axi_11_27_ },
    { &KinematicsSolver::calc_Axi_12_1_, &KinematicsSolver::calc_Axi_12_2_, &KinematicsSolver::calc_Axi_12_3_, &KinematicsSolver::calc_Axi_12_4_, &KinematicsSolver::calc_Axi_12_5_, &KinematicsSolver::calc_Axi_12_6_, &KinematicsSolver::calc_Axi_12_7_, &KinematicsSolver::calc_Axi_12_8_, &KinematicsSolver::calc_Axi_12_9_, &KinematicsSolver::calc_Axi_12_10_, &KinematicsSolver::calc_Axi_12_11_, &KinematicsSolver::calc_Axi_12_12_, &KinematicsSolver::calc_Axi_12_13_, &KinematicsSolver::calc_Axi_12_14_, &KinematicsSolver::calc_Axi_12_15_, &KinematicsSolver::calc_Axi_12_16_, &KinematicsSolver::calc_Axi_12_17_, &KinematicsSolver::calc_Axi_12_18_, &KinematicsSolver::calc_Axi_12_19_, &KinematicsSolver::calc_Axi_12_20_, &KinematicsSolver::calc_Axi_12_21_, &KinematicsSolver::calc_Axi_12_22_, &KinematicsSolver::calc_Axi_12_23_, &KinematicsSolver::calc_Axi_12_24_, &KinematicsSolver::calc_Axi_12_25_, &KinematicsSolver::calc_Axi_12_26_, &KinematicsSolver::calc_Axi_12_27_ },
    { &KinematicsSolver::calc_Axi_13_1_, &KinematicsSolver::calc_Axi_13_2_, &KinematicsSolver::calc_Axi_13_3_, &KinematicsSolver::calc_Axi_13_4_, &KinematicsSolver::calc_Axi_13_5_, &KinematicsSolver::calc_Axi_13_6_, &KinematicsSolver::calc_Axi_13_7_, &KinematicsSolver::calc_Axi_13_8_, &KinematicsSolver::calc_Axi_13_9_, &KinematicsSolver::calc_Axi_13_10_, &KinematicsSolver::calc_Axi_13_11_, &KinematicsSolver::calc_Axi_13_12_, &KinematicsSolver::calc_Axi_13_13_, &KinematicsSolver::calc_Axi_13_14_, &KinematicsSolver::calc_Axi_13_15_, &KinematicsSolver::calc_Axi_13_16_, &KinematicsSolver::calc_Axi_13_17_, &KinematicsSolver::calc_Axi_13_18_, &KinematicsSolver::calc_Axi_13_19_, &KinematicsSolver::calc_Axi_13_20_, &KinematicsSolver::calc_Axi_13_21_, &KinematicsSolver::calc_Axi_13_22_, &KinematicsSolver::calc_Axi_13_23_, &KinematicsSolver::calc_Axi_13_24_, &KinematicsSolver::calc_Axi_13_25_, &KinematicsSolver::calc_Axi_13_26_, &KinematicsSolver::calc_Axi_13_27_ },
    { &KinematicsSolver::calc_Axi_14_1_, &KinematicsSolver::calc_Axi_14_2_, &KinematicsSolver::calc_Axi_14_3_, &KinematicsSolver::calc_Axi_14_4_, &KinematicsSolver::calc_Axi_14_5_, &KinematicsSolver::calc_Axi_14_6_, &KinematicsSolver::calc_Axi_14_7_, &KinematicsSolver::calc_Axi_14_8_, &KinematicsSolver::calc_Axi_14_9_, &KinematicsSolver::calc_Axi_14_10_, &KinematicsSolver::calc_Axi_14_11_, &KinematicsSolver::calc_Axi_14_12_, &KinematicsSolver::calc_Axi_14_13_, &KinematicsSolver::calc_Axi_14_14_, &KinematicsSolver::calc_Axi_14_15_, &KinematicsSolver::calc_Axi_14_16_, &KinematicsSolver::calc_Axi_14_17_, &KinematicsSolver::calc_Axi_14_18_, &KinematicsSolver::calc_Axi_14_19_, &KinematicsSolver::calc_Axi_14_20_, &KinematicsSolver::calc_Axi_14_21_, &KinematicsSolver::calc_Axi_14_22_, &KinematicsSolver::calc_Axi_14_23_, &KinematicsSolver::calc_Axi_14_24_, &KinematicsSolver::calc_Axi_14_25_, &KinematicsSolver::calc_Axi_14_26_, &KinematicsSolver::calc_Axi_14_27_ },
    { &KinematicsSolver::calc_Axi_15_1_, &KinematicsSolver::calc_Axi_15_2_, &KinematicsSolver::calc_Axi_15_3_, &KinematicsSolver::calc_Axi_15_4_, &KinematicsSolver::calc_Axi_15_5_, &KinematicsSolver::calc_Axi_15_6_, &KinematicsSolver::calc_Axi_15_7_, &KinematicsSolver::calc_Axi_15_8_, &KinematicsSolver::calc_Axi_15_9_, &KinematicsSolver::calc_Axi_15_10_, &KinematicsSolver::calc_Axi_15_11_, &KinematicsSolver::calc_Axi_15_12_, &KinematicsSolver::calc_Axi_15_13_, &KinematicsSolver::calc_Axi_15_14_, &KinematicsSolver::calc_Axi_15_15_, &KinematicsSolver::calc_Axi_15_16_, &KinematicsSolver::calc_Axi_15_17_, &KinematicsSolver::calc_Axi_15_18_, &KinematicsSolver::calc_Axi_15_19_, &KinematicsSolver::calc_Axi_15_20_, &KinematicsSolver::calc_Axi_15_21_, &KinematicsSolver::calc_Axi_15_22_, &KinematicsSolver::calc_Axi_15_23_, &KinematicsSolver::calc_Axi_15_24_, &KinematicsSolver::calc_Axi_15_25_, &KinematicsSolver::calc_Axi_15_26_, &KinematicsSolver::calc_Axi_15_27_ },
    { &KinematicsSolver::calc_Axi_16_1_, &KinematicsSolver::calc_Axi_16_2_, &KinematicsSolver::calc_Axi_16_3_, &KinematicsSolver::calc_Axi_16_4_, &KinematicsSolver::calc_Axi_16_5_, &KinematicsSolver::calc_Axi_16_6_, &KinematicsSolver::calc_Axi_16_7_, &KinematicsSolver::calc_Axi_16_8_, &KinematicsSolver::calc_Axi_16_9_, &KinematicsSolver::calc_Axi_16_10_, &KinematicsSolver::calc_Axi_16_11_, &KinematicsSolver::calc_Axi_16_12_, &KinematicsSolver::calc_Axi_16_13_, &KinematicsSolver::calc_Axi_16_14_, &KinematicsSolver::calc_Axi_16_15_, &KinematicsSolver::calc_Axi_16_16_, &KinematicsSolver::calc_Axi_16_17_, &KinematicsSolver::calc_Axi_16_18_, &KinematicsSolver::calc_Axi_16_19_, &KinematicsSolver::calc_Axi_16_20_, &KinematicsSolver::calc_Axi_16_21_, &KinematicsSolver::calc_Axi_16_22_, &KinematicsSolver::calc_Axi_16_23_, &KinematicsSolver::calc_Axi_16_24_, &KinematicsSolver::calc_Axi_16_25_, &KinematicsSolver::calc_Axi_16_26_, &KinematicsSolver::calc_Axi_16_27_ },
    { &KinematicsSolver::calc_Axi_17_1_, &KinematicsSolver::calc_Axi_17_2_, &KinematicsSolver::calc_Axi_17_3_, &KinematicsSolver::calc_Axi_17_4_, &KinematicsSolver::calc_Axi_17_5_, &KinematicsSolver::calc_Axi_17_6_, &KinematicsSolver::calc_Axi_17_7_, &KinematicsSolver::calc_Axi_17_8_, &KinematicsSolver::calc_Axi_17_9_, &KinematicsSolver::calc_Axi_17_10_, &KinematicsSolver::calc_Axi_17_11_, &KinematicsSolver::calc_Axi_17_12_, &KinematicsSolver::calc_Axi_17_13_, &KinematicsSolver::calc_Axi_17_14_, &KinematicsSolver::calc_Axi_17_15_, &KinematicsSolver::calc_Axi_17_16_, &KinematicsSolver::calc_Axi_17_17_, &KinematicsSolver::calc_Axi_17_18_, &KinematicsSolver::calc_Axi_17_19_, &KinematicsSolver::calc_Axi_17_20_, &KinematicsSolver::calc_Axi_17_21_, &KinematicsSolver::calc_Axi_17_22_, &KinematicsSolver::calc_Axi_17_23_, &KinematicsSolver::calc_Axi_17_24_, &KinematicsSolver::calc_Axi_17_25_, &KinematicsSolver::calc_Axi_17_26_, &KinematicsSolver::calc_Axi_17_27_ },
    { &KinematicsSolver::calc_Axi_18_1_, &KinematicsSolver::calc_Axi_18_2_, &KinematicsSolver::calc_Axi_18_3_, &KinematicsSolver::calc_Axi_18_4_, &KinematicsSolver::calc_Axi_18_5_, &KinematicsSolver::calc_Axi_18_6_, &KinematicsSolver::calc_Axi_18_7_, &KinematicsSolver::calc_Axi_18_8_, &KinematicsSolver::calc_Axi_18_9_, &KinematicsSolver::calc_Axi_18_10_, &KinematicsSolver::calc_Axi_18_11_, &KinematicsSolver::calc_Axi_18_12_, &KinematicsSolver::calc_Axi_18_13_, &KinematicsSolver::calc_Axi_18_14_, &KinematicsSolver::calc_Axi_18_15_, &KinematicsSolver::calc_Axi_18_16_, &KinematicsSolver::calc_Axi_18_17_, &KinematicsSolver::calc_Axi_18_18_, &KinematicsSolver::calc_Axi_18_19_, &KinematicsSolver::calc_Axi_18_20_, &KinematicsSolver::calc_Axi_18_21_, &KinematicsSolver::calc_Axi_18_22_, &KinematicsSolver::calc_Axi_18_23_, &KinematicsSolver::calc_Axi_18_24_, &KinematicsSolver::calc_Axi_18_25_, &KinematicsSolver::calc_Axi_18_26_, &KinematicsSolver::calc_Axi_18_27_ }
  };
  
  
  
  //Kxi
  inline static constexpr Mfn Kxi_tbl[27] = {
    &KinematicsSolver::calc_Kxi_1_,  &KinematicsSolver::calc_Kxi_2_,  &KinematicsSolver::calc_Kxi_3_,  &KinematicsSolver::calc_Kxi_4_,
    &KinematicsSolver::calc_Kxi_5_,  &KinematicsSolver::calc_Kxi_6_,  &KinematicsSolver::calc_Kxi_7_,  &KinematicsSolver::calc_Kxi_8_,
    &KinematicsSolver::calc_Kxi_9_,  &KinematicsSolver::calc_Kxi_10_, &KinematicsSolver::calc_Kxi_11_, &KinematicsSolver::calc_Kxi_12_,
    &KinematicsSolver::calc_Kxi_13_, &KinematicsSolver::calc_Kxi_14_, &KinematicsSolver::calc_Kxi_15_, &KinematicsSolver::calc_Kxi_16_,
    &KinematicsSolver::calc_Kxi_17_, &KinematicsSolver::calc_Kxi_18_, &KinematicsSolver::calc_Kxi_19_, &KinematicsSolver::calc_Kxi_20_,
    &KinematicsSolver::calc_Kxi_21_, &KinematicsSolver::calc_Kxi_22_, &KinematicsSolver::calc_Kxi_23_, &KinematicsSolver::calc_Kxi_24_,
    &KinematicsSolver::calc_Kxi_25_, &KinematicsSolver::calc_Kxi_26_, &KinematicsSolver::calc_Kxi_27_};
  
  
  // --- SX 23x12 ---
  inline static constexpr Mfn SX_tbl[23][12] = {
    { &KinematicsSolver::calc_SX_1_1_, &KinematicsSolver::calc_SX_1_2_, &KinematicsSolver::calc_SX_1_3_, &KinematicsSolver::calc_SX_1_4_, &KinematicsSolver::calc_SX_1_5_, &KinematicsSolver::calc_SX_1_6_, &KinematicsSolver::calc_SX_1_7_, &KinematicsSolver::calc_SX_1_8_, &KinematicsSolver::calc_SX_1_9_, &KinematicsSolver::calc_SX_1_10_, &KinematicsSolver::calc_SX_1_11_, &KinematicsSolver::calc_SX_1_12_ },
    { &KinematicsSolver::calc_SX_2_1_, &KinematicsSolver::calc_SX_2_2_, &KinematicsSolver::calc_SX_2_3_, &KinematicsSolver::calc_SX_2_4_, &KinematicsSolver::calc_SX_2_5_, &KinematicsSolver::calc_SX_2_6_, &KinematicsSolver::calc_SX_2_7_, &KinematicsSolver::calc_SX_2_8_, &KinematicsSolver::calc_SX_2_9_, &KinematicsSolver::calc_SX_2_10_, &KinematicsSolver::calc_SX_2_11_, &KinematicsSolver::calc_SX_2_12_ },
    { &KinematicsSolver::calc_SX_3_1_, &KinematicsSolver::calc_SX_3_2_, &KinematicsSolver::calc_SX_3_3_, &KinematicsSolver::calc_SX_3_4_, &KinematicsSolver::calc_SX_3_5_, &KinematicsSolver::calc_SX_3_6_, &KinematicsSolver::calc_SX_3_7_, &KinematicsSolver::calc_SX_3_8_, &KinematicsSolver::calc_SX_3_9_, &KinematicsSolver::calc_SX_3_10_, &KinematicsSolver::calc_SX_3_11_, &KinematicsSolver::calc_SX_3_12_ },
    { &KinematicsSolver::calc_SX_4_1_, &KinematicsSolver::calc_SX_4_2_, &KinematicsSolver::calc_SX_4_3_, &KinematicsSolver::calc_SX_4_4_, &KinematicsSolver::calc_SX_4_5_, &KinematicsSolver::calc_SX_4_6_, &KinematicsSolver::calc_SX_4_7_, &KinematicsSolver::calc_SX_4_8_, &KinematicsSolver::calc_SX_4_9_, &KinematicsSolver::calc_SX_4_10_, &KinematicsSolver::calc_SX_4_11_, &KinematicsSolver::calc_SX_4_12_ },
    { &KinematicsSolver::calc_SX_5_1_, &KinematicsSolver::calc_SX_5_2_, &KinematicsSolver::calc_SX_5_3_, &KinematicsSolver::calc_SX_5_4_, &KinematicsSolver::calc_SX_5_5_, &KinematicsSolver::calc_SX_5_6_, &KinematicsSolver::calc_SX_5_7_, &KinematicsSolver::calc_SX_5_8_, &KinematicsSolver::calc_SX_5_9_, &KinematicsSolver::calc_SX_5_10_, &KinematicsSolver::calc_SX_5_11_, &KinematicsSolver::calc_SX_5_12_ },
    { &KinematicsSolver::calc_SX_6_1_, &KinematicsSolver::calc_SX_6_2_, &KinematicsSolver::calc_SX_6_3_, &KinematicsSolver::calc_SX_6_4_, &KinematicsSolver::calc_SX_6_5_, &KinematicsSolver::calc_SX_6_6_, &KinematicsSolver::calc_SX_6_7_, &KinematicsSolver::calc_SX_6_8_, &KinematicsSolver::calc_SX_6_9_, &KinematicsSolver::calc_SX_6_10_, &KinematicsSolver::calc_SX_6_11_, &KinematicsSolver::calc_SX_6_12_ },
    { &KinematicsSolver::calc_SX_7_1_, &KinematicsSolver::calc_SX_7_2_, &KinematicsSolver::calc_SX_7_3_, &KinematicsSolver::calc_SX_7_4_, &KinematicsSolver::calc_SX_7_5_, &KinematicsSolver::calc_SX_7_6_, &KinematicsSolver::calc_SX_7_7_, &KinematicsSolver::calc_SX_7_8_, &KinematicsSolver::calc_SX_7_9_, &KinematicsSolver::calc_SX_7_10_, &KinematicsSolver::calc_SX_7_11_, &KinematicsSolver::calc_SX_7_12_ },
    { &KinematicsSolver::calc_SX_8_1_, &KinematicsSolver::calc_SX_8_2_, &KinematicsSolver::calc_SX_8_3_, &KinematicsSolver::calc_SX_8_4_, &KinematicsSolver::calc_SX_8_5_, &KinematicsSolver::calc_SX_8_6_, &KinematicsSolver::calc_SX_8_7_, &KinematicsSolver::calc_SX_8_8_, &KinematicsSolver::calc_SX_8_9_, &KinematicsSolver::calc_SX_8_10_, &KinematicsSolver::calc_SX_8_11_, &KinematicsSolver::calc_SX_8_12_ },
    { &KinematicsSolver::calc_SX_9_1_, &KinematicsSolver::calc_SX_9_2_, &KinematicsSolver::calc_SX_9_3_, &KinematicsSolver::calc_SX_9_4_, &KinematicsSolver::calc_SX_9_5_, &KinematicsSolver::calc_SX_9_6_, &KinematicsSolver::calc_SX_9_7_, &KinematicsSolver::calc_SX_9_8_, &KinematicsSolver::calc_SX_9_9_, &KinematicsSolver::calc_SX_9_10_, &KinematicsSolver::calc_SX_9_11_, &KinematicsSolver::calc_SX_9_12_ },
    { &KinematicsSolver::calc_SX_10_1_, &KinematicsSolver::calc_SX_10_2_, &KinematicsSolver::calc_SX_10_3_, &KinematicsSolver::calc_SX_10_4_, &KinematicsSolver::calc_SX_10_5_, &KinematicsSolver::calc_SX_10_6_, &KinematicsSolver::calc_SX_10_7_, &KinematicsSolver::calc_SX_10_8_, &KinematicsSolver::calc_SX_10_9_, &KinematicsSolver::calc_SX_10_10_, &KinematicsSolver::calc_SX_10_11_, &KinematicsSolver::calc_SX_10_12_ },
    { &KinematicsSolver::calc_SX_11_1_, &KinematicsSolver::calc_SX_11_2_, &KinematicsSolver::calc_SX_11_3_, &KinematicsSolver::calc_SX_11_4_, &KinematicsSolver::calc_SX_11_5_, &KinematicsSolver::calc_SX_11_6_, &KinematicsSolver::calc_SX_11_7_, &KinematicsSolver::calc_SX_11_8_, &KinematicsSolver::calc_SX_11_9_, &KinematicsSolver::calc_SX_11_10_, &KinematicsSolver::calc_SX_11_11_, &KinematicsSolver::calc_SX_11_12_ },
    { &KinematicsSolver::calc_SX_12_1_, &KinematicsSolver::calc_SX_12_2_, &KinematicsSolver::calc_SX_12_3_, &KinematicsSolver::calc_SX_12_4_, &KinematicsSolver::calc_SX_12_5_, &KinematicsSolver::calc_SX_12_6_, &KinematicsSolver::calc_SX_12_7_, &KinematicsSolver::calc_SX_12_8_, &KinematicsSolver::calc_SX_12_9_, &KinematicsSolver::calc_SX_12_10_, &KinematicsSolver::calc_SX_12_11_, &KinematicsSolver::calc_SX_12_12_ },
    { &KinematicsSolver::calc_SX_13_1_, &KinematicsSolver::calc_SX_13_2_, &KinematicsSolver::calc_SX_13_3_, &KinematicsSolver::calc_SX_13_4_, &KinematicsSolver::calc_SX_13_5_, &KinematicsSolver::calc_SX_13_6_, &KinematicsSolver::calc_SX_13_7_, &KinematicsSolver::calc_SX_13_8_, &KinematicsSolver::calc_SX_13_9_, &KinematicsSolver::calc_SX_13_10_, &KinematicsSolver::calc_SX_13_11_, &KinematicsSolver::calc_SX_13_12_ },
    { &KinematicsSolver::calc_SX_14_1_, &KinematicsSolver::calc_SX_14_2_, &KinematicsSolver::calc_SX_14_3_, &KinematicsSolver::calc_SX_14_4_, &KinematicsSolver::calc_SX_14_5_, &KinematicsSolver::calc_SX_14_6_, &KinematicsSolver::calc_SX_14_7_, &KinematicsSolver::calc_SX_14_8_, &KinematicsSolver::calc_SX_14_9_, &KinematicsSolver::calc_SX_14_10_, &KinematicsSolver::calc_SX_14_11_, &KinematicsSolver::calc_SX_14_12_ },
    { &KinematicsSolver::calc_SX_15_1_, &KinematicsSolver::calc_SX_15_2_, &KinematicsSolver::calc_SX_15_3_, &KinematicsSolver::calc_SX_15_4_, &KinematicsSolver::calc_SX_15_5_, &KinematicsSolver::calc_SX_15_6_, &KinematicsSolver::calc_SX_15_7_, &KinematicsSolver::calc_SX_15_8_, &KinematicsSolver::calc_SX_15_9_, &KinematicsSolver::calc_SX_15_10_, &KinematicsSolver::calc_SX_15_11_, &KinematicsSolver::calc_SX_15_12_ },
    { &KinematicsSolver::calc_SX_16_1_, &KinematicsSolver::calc_SX_16_2_, &KinematicsSolver::calc_SX_16_3_, &KinematicsSolver::calc_SX_16_4_, &KinematicsSolver::calc_SX_16_5_, &KinematicsSolver::calc_SX_16_6_, &KinematicsSolver::calc_SX_16_7_, &KinematicsSolver::calc_SX_16_8_, &KinematicsSolver::calc_SX_16_9_, &KinematicsSolver::calc_SX_16_10_, &KinematicsSolver::calc_SX_16_11_, &KinematicsSolver::calc_SX_16_12_ },
    { &KinematicsSolver::calc_SX_17_1_, &KinematicsSolver::calc_SX_17_2_, &KinematicsSolver::calc_SX_17_3_, &KinematicsSolver::calc_SX_17_4_, &KinematicsSolver::calc_SX_17_5_, &KinematicsSolver::calc_SX_17_6_, &KinematicsSolver::calc_SX_17_7_, &KinematicsSolver::calc_SX_17_8_, &KinematicsSolver::calc_SX_17_9_, &KinematicsSolver::calc_SX_17_10_, &KinematicsSolver::calc_SX_17_11_, &KinematicsSolver::calc_SX_17_12_ },
    { &KinematicsSolver::calc_SX_18_1_, &KinematicsSolver::calc_SX_18_2_, &KinematicsSolver::calc_SX_18_3_, &KinematicsSolver::calc_SX_18_4_, &KinematicsSolver::calc_SX_18_5_, &KinematicsSolver::calc_SX_18_6_, &KinematicsSolver::calc_SX_18_7_, &KinematicsSolver::calc_SX_18_8_, &KinematicsSolver::calc_SX_18_9_, &KinematicsSolver::calc_SX_18_10_, &KinematicsSolver::calc_SX_18_11_, &KinematicsSolver::calc_SX_18_12_ },
    { &KinematicsSolver::calc_SX_19_1_, &KinematicsSolver::calc_SX_19_2_, &KinematicsSolver::calc_SX_19_3_, &KinematicsSolver::calc_SX_19_4_, &KinematicsSolver::calc_SX_19_5_, &KinematicsSolver::calc_SX_19_6_, &KinematicsSolver::calc_SX_19_7_, &KinematicsSolver::calc_SX_19_8_, &KinematicsSolver::calc_SX_19_9_, &KinematicsSolver::calc_SX_19_10_, &KinematicsSolver::calc_SX_19_11_, &KinematicsSolver::calc_SX_19_12_ },
    { &KinematicsSolver::calc_SX_20_1_, &KinematicsSolver::calc_SX_20_2_, &KinematicsSolver::calc_SX_20_3_, &KinematicsSolver::calc_SX_20_4_, &KinematicsSolver::calc_SX_20_5_, &KinematicsSolver::calc_SX_20_6_, &KinematicsSolver::calc_SX_20_7_, &KinematicsSolver::calc_SX_20_8_, &KinematicsSolver::calc_SX_20_9_, &KinematicsSolver::calc_SX_20_10_, &KinematicsSolver::calc_SX_20_11_, &KinematicsSolver::calc_SX_20_12_ },
    { &KinematicsSolver::calc_SX_21_1_, &KinematicsSolver::calc_SX_21_2_, &KinematicsSolver::calc_SX_21_3_, &KinematicsSolver::calc_SX_21_4_, &KinematicsSolver::calc_SX_21_5_, &KinematicsSolver::calc_SX_21_6_, &KinematicsSolver::calc_SX_21_7_, &KinematicsSolver::calc_SX_21_8_, &KinematicsSolver::calc_SX_21_9_, &KinematicsSolver::calc_SX_21_10_, &KinematicsSolver::calc_SX_21_11_, &KinematicsSolver::calc_SX_21_12_ },
    { &KinematicsSolver::calc_SX_22_1_, &KinematicsSolver::calc_SX_22_2_, &KinematicsSolver::calc_SX_22_3_, &KinematicsSolver::calc_SX_22_4_, &KinematicsSolver::calc_SX_22_5_, &KinematicsSolver::calc_SX_22_6_, &KinematicsSolver::calc_SX_22_7_, &KinematicsSolver::calc_SX_22_8_, &KinematicsSolver::calc_SX_22_9_, &KinematicsSolver::calc_SX_22_10_, &KinematicsSolver::calc_SX_22_11_, &KinematicsSolver::calc_SX_22_12_ },
    { &KinematicsSolver::calc_SX_23_1_, &KinematicsSolver::calc_SX_23_2_, &KinematicsSolver::calc_SX_23_3_, &KinematicsSolver::calc_SX_23_4_, &KinematicsSolver::calc_SX_23_5_, &KinematicsSolver::calc_SX_23_6_, &KinematicsSolver::calc_SX_23_7_, &KinematicsSolver::calc_SX_23_8_, &KinematicsSolver::calc_SX_23_9_, &KinematicsSolver::calc_SX_23_10_, &KinematicsSolver::calc_SX_23_11_, &KinematicsSolver::calc_SX_23_12_ }
  };
  
  
  
  // --- d_SX_d_t 23x12 ---
  inline static constexpr Mfn dSXdt_tbl[23][12] = {
    { &KinematicsSolver::calc_d_SX_d_t_1_1_, &KinematicsSolver::calc_d_SX_d_t_1_2_, &KinematicsSolver::calc_d_SX_d_t_1_3_, &KinematicsSolver::calc_d_SX_d_t_1_4_, &KinematicsSolver::calc_d_SX_d_t_1_5_, &KinematicsSolver::calc_d_SX_d_t_1_6_, &KinematicsSolver::calc_d_SX_d_t_1_7_, &KinematicsSolver::calc_d_SX_d_t_1_8_, &KinematicsSolver::calc_d_SX_d_t_1_9_, &KinematicsSolver::calc_d_SX_d_t_1_10_, &KinematicsSolver::calc_d_SX_d_t_1_11_, &KinematicsSolver::calc_d_SX_d_t_1_12_ },
    { &KinematicsSolver::calc_d_SX_d_t_2_1_, &KinematicsSolver::calc_d_SX_d_t_2_2_, &KinematicsSolver::calc_d_SX_d_t_2_3_, &KinematicsSolver::calc_d_SX_d_t_2_4_, &KinematicsSolver::calc_d_SX_d_t_2_5_, &KinematicsSolver::calc_d_SX_d_t_2_6_, &KinematicsSolver::calc_d_SX_d_t_2_7_, &KinematicsSolver::calc_d_SX_d_t_2_8_, &KinematicsSolver::calc_d_SX_d_t_2_9_, &KinematicsSolver::calc_d_SX_d_t_2_10_, &KinematicsSolver::calc_d_SX_d_t_2_11_, &KinematicsSolver::calc_d_SX_d_t_2_12_ },
    { &KinematicsSolver::calc_d_SX_d_t_3_1_, &KinematicsSolver::calc_d_SX_d_t_3_2_, &KinematicsSolver::calc_d_SX_d_t_3_3_, &KinematicsSolver::calc_d_SX_d_t_3_4_, &KinematicsSolver::calc_d_SX_d_t_3_5_, &KinematicsSolver::calc_d_SX_d_t_3_6_, &KinematicsSolver::calc_d_SX_d_t_3_7_, &KinematicsSolver::calc_d_SX_d_t_3_8_, &KinematicsSolver::calc_d_SX_d_t_3_9_, &KinematicsSolver::calc_d_SX_d_t_3_10_, &KinematicsSolver::calc_d_SX_d_t_3_11_, &KinematicsSolver::calc_d_SX_d_t_3_12_ },
    { &KinematicsSolver::calc_d_SX_d_t_4_1_, &KinematicsSolver::calc_d_SX_d_t_4_2_, &KinematicsSolver::calc_d_SX_d_t_4_3_, &KinematicsSolver::calc_d_SX_d_t_4_4_, &KinematicsSolver::calc_d_SX_d_t_4_5_, &KinematicsSolver::calc_d_SX_d_t_4_6_, &KinematicsSolver::calc_d_SX_d_t_4_7_, &KinematicsSolver::calc_d_SX_d_t_4_8_, &KinematicsSolver::calc_d_SX_d_t_4_9_, &KinematicsSolver::calc_d_SX_d_t_4_10_, &KinematicsSolver::calc_d_SX_d_t_4_11_, &KinematicsSolver::calc_d_SX_d_t_4_12_ },
    { &KinematicsSolver::calc_d_SX_d_t_5_1_, &KinematicsSolver::calc_d_SX_d_t_5_2_, &KinematicsSolver::calc_d_SX_d_t_5_3_, &KinematicsSolver::calc_d_SX_d_t_5_4_, &KinematicsSolver::calc_d_SX_d_t_5_5_, &KinematicsSolver::calc_d_SX_d_t_5_6_, &KinematicsSolver::calc_d_SX_d_t_5_7_, &KinematicsSolver::calc_d_SX_d_t_5_8_, &KinematicsSolver::calc_d_SX_d_t_5_9_, &KinematicsSolver::calc_d_SX_d_t_5_10_, &KinematicsSolver::calc_d_SX_d_t_5_11_, &KinematicsSolver::calc_d_SX_d_t_5_12_ },
    { &KinematicsSolver::calc_d_SX_d_t_6_1_, &KinematicsSolver::calc_d_SX_d_t_6_2_, &KinematicsSolver::calc_d_SX_d_t_6_3_, &KinematicsSolver::calc_d_SX_d_t_6_4_, &KinematicsSolver::calc_d_SX_d_t_6_5_, &KinematicsSolver::calc_d_SX_d_t_6_6_, &KinematicsSolver::calc_d_SX_d_t_6_7_, &KinematicsSolver::calc_d_SX_d_t_6_8_, &KinematicsSolver::calc_d_SX_d_t_6_9_, &KinematicsSolver::calc_d_SX_d_t_6_10_, &KinematicsSolver::calc_d_SX_d_t_6_11_, &KinematicsSolver::calc_d_SX_d_t_6_12_ },
    { &KinematicsSolver::calc_d_SX_d_t_7_1_, &KinematicsSolver::calc_d_SX_d_t_7_2_, &KinematicsSolver::calc_d_SX_d_t_7_3_, &KinematicsSolver::calc_d_SX_d_t_7_4_, &KinematicsSolver::calc_d_SX_d_t_7_5_, &KinematicsSolver::calc_d_SX_d_t_7_6_, &KinematicsSolver::calc_d_SX_d_t_7_7_, &KinematicsSolver::calc_d_SX_d_t_7_8_, &KinematicsSolver::calc_d_SX_d_t_7_9_, &KinematicsSolver::calc_d_SX_d_t_7_10_, &KinematicsSolver::calc_d_SX_d_t_7_11_, &KinematicsSolver::calc_d_SX_d_t_7_12_ },
    { &KinematicsSolver::calc_d_SX_d_t_8_1_, &KinematicsSolver::calc_d_SX_d_t_8_2_, &KinematicsSolver::calc_d_SX_d_t_8_3_, &KinematicsSolver::calc_d_SX_d_t_8_4_, &KinematicsSolver::calc_d_SX_d_t_8_5_, &KinematicsSolver::calc_d_SX_d_t_8_6_, &KinematicsSolver::calc_d_SX_d_t_8_7_, &KinematicsSolver::calc_d_SX_d_t_8_8_, &KinematicsSolver::calc_d_SX_d_t_8_9_, &KinematicsSolver::calc_d_SX_d_t_8_10_, &KinematicsSolver::calc_d_SX_d_t_8_11_, &KinematicsSolver::calc_d_SX_d_t_8_12_ },
    { &KinematicsSolver::calc_d_SX_d_t_9_1_, &KinematicsSolver::calc_d_SX_d_t_9_2_, &KinematicsSolver::calc_d_SX_d_t_9_3_, &KinematicsSolver::calc_d_SX_d_t_9_4_, &KinematicsSolver::calc_d_SX_d_t_9_5_, &KinematicsSolver::calc_d_SX_d_t_9_6_, &KinematicsSolver::calc_d_SX_d_t_9_7_, &KinematicsSolver::calc_d_SX_d_t_9_8_, &KinematicsSolver::calc_d_SX_d_t_9_9_, &KinematicsSolver::calc_d_SX_d_t_9_10_, &KinematicsSolver::calc_d_SX_d_t_9_11_, &KinematicsSolver::calc_d_SX_d_t_9_12_ },
    { &KinematicsSolver::calc_d_SX_d_t_10_1_, &KinematicsSolver::calc_d_SX_d_t_10_2_, &KinematicsSolver::calc_d_SX_d_t_10_3_, &KinematicsSolver::calc_d_SX_d_t_10_4_, &KinematicsSolver::calc_d_SX_d_t_10_5_, &KinematicsSolver::calc_d_SX_d_t_10_6_, &KinematicsSolver::calc_d_SX_d_t_10_7_, &KinematicsSolver::calc_d_SX_d_t_10_8_, &KinematicsSolver::calc_d_SX_d_t_10_9_, &KinematicsSolver::calc_d_SX_d_t_10_10_, &KinematicsSolver::calc_d_SX_d_t_10_11_, &KinematicsSolver::calc_d_SX_d_t_10_12_ },
    { &KinematicsSolver::calc_d_SX_d_t_11_1_, &KinematicsSolver::calc_d_SX_d_t_11_2_, &KinematicsSolver::calc_d_SX_d_t_11_3_, &KinematicsSolver::calc_d_SX_d_t_11_4_, &KinematicsSolver::calc_d_SX_d_t_11_5_, &KinematicsSolver::calc_d_SX_d_t_11_6_, &KinematicsSolver::calc_d_SX_d_t_11_7_, &KinematicsSolver::calc_d_SX_d_t_11_8_, &KinematicsSolver::calc_d_SX_d_t_11_9_, &KinematicsSolver::calc_d_SX_d_t_11_10_, &KinematicsSolver::calc_d_SX_d_t_11_11_, &KinematicsSolver::calc_d_SX_d_t_11_12_ },
    { &KinematicsSolver::calc_d_SX_d_t_12_1_, &KinematicsSolver::calc_d_SX_d_t_12_2_, &KinematicsSolver::calc_d_SX_d_t_12_3_, &KinematicsSolver::calc_d_SX_d_t_12_4_, &KinematicsSolver::calc_d_SX_d_t_12_5_, &KinematicsSolver::calc_d_SX_d_t_12_6_, &KinematicsSolver::calc_d_SX_d_t_12_7_, &KinematicsSolver::calc_d_SX_d_t_12_8_, &KinematicsSolver::calc_d_SX_d_t_12_9_, &KinematicsSolver::calc_d_SX_d_t_12_10_, &KinematicsSolver::calc_d_SX_d_t_12_11_, &KinematicsSolver::calc_d_SX_d_t_12_12_ },
    { &KinematicsSolver::calc_d_SX_d_t_13_1_, &KinematicsSolver::calc_d_SX_d_t_13_2_, &KinematicsSolver::calc_d_SX_d_t_13_3_, &KinematicsSolver::calc_d_SX_d_t_13_4_, &KinematicsSolver::calc_d_SX_d_t_13_5_, &KinematicsSolver::calc_d_SX_d_t_13_6_, &KinematicsSolver::calc_d_SX_d_t_13_7_, &KinematicsSolver::calc_d_SX_d_t_13_8_, &KinematicsSolver::calc_d_SX_d_t_13_9_, &KinematicsSolver::calc_d_SX_d_t_13_10_, &KinematicsSolver::calc_d_SX_d_t_13_11_, &KinematicsSolver::calc_d_SX_d_t_13_12_ },
    { &KinematicsSolver::calc_d_SX_d_t_14_1_, &KinematicsSolver::calc_d_SX_d_t_14_2_, &KinematicsSolver::calc_d_SX_d_t_14_3_, &KinematicsSolver::calc_d_SX_d_t_14_4_, &KinematicsSolver::calc_d_SX_d_t_14_5_, &KinematicsSolver::calc_d_SX_d_t_14_6_, &KinematicsSolver::calc_d_SX_d_t_14_7_, &KinematicsSolver::calc_d_SX_d_t_14_8_, &KinematicsSolver::calc_d_SX_d_t_14_9_, &KinematicsSolver::calc_d_SX_d_t_14_10_, &KinematicsSolver::calc_d_SX_d_t_14_11_, &KinematicsSolver::calc_d_SX_d_t_14_12_ },
    { &KinematicsSolver::calc_d_SX_d_t_15_1_, &KinematicsSolver::calc_d_SX_d_t_15_2_, &KinematicsSolver::calc_d_SX_d_t_15_3_, &KinematicsSolver::calc_d_SX_d_t_15_4_, &KinematicsSolver::calc_d_SX_d_t_15_5_, &KinematicsSolver::calc_d_SX_d_t_15_6_, &KinematicsSolver::calc_d_SX_d_t_15_7_, &KinematicsSolver::calc_d_SX_d_t_15_8_, &KinematicsSolver::calc_d_SX_d_t_15_9_, &KinematicsSolver::calc_d_SX_d_t_15_10_, &KinematicsSolver::calc_d_SX_d_t_15_11_, &KinematicsSolver::calc_d_SX_d_t_15_12_ },
    { &KinematicsSolver::calc_d_SX_d_t_16_1_, &KinematicsSolver::calc_d_SX_d_t_16_2_, &KinematicsSolver::calc_d_SX_d_t_16_3_, &KinematicsSolver::calc_d_SX_d_t_16_4_, &KinematicsSolver::calc_d_SX_d_t_16_5_, &KinematicsSolver::calc_d_SX_d_t_16_6_, &KinematicsSolver::calc_d_SX_d_t_16_7_, &KinematicsSolver::calc_d_SX_d_t_16_8_, &KinematicsSolver::calc_d_SX_d_t_16_9_, &KinematicsSolver::calc_d_SX_d_t_16_10_, &KinematicsSolver::calc_d_SX_d_t_16_11_, &KinematicsSolver::calc_d_SX_d_t_16_12_ },
    { &KinematicsSolver::calc_d_SX_d_t_17_1_, &KinematicsSolver::calc_d_SX_d_t_17_2_, &KinematicsSolver::calc_d_SX_d_t_17_3_, &KinematicsSolver::calc_d_SX_d_t_17_4_, &KinematicsSolver::calc_d_SX_d_t_17_5_, &KinematicsSolver::calc_d_SX_d_t_17_6_, &KinematicsSolver::calc_d_SX_d_t_17_7_, &KinematicsSolver::calc_d_SX_d_t_17_8_, &KinematicsSolver::calc_d_SX_d_t_17_9_, &KinematicsSolver::calc_d_SX_d_t_17_10_, &KinematicsSolver::calc_d_SX_d_t_17_11_, &KinematicsSolver::calc_d_SX_d_t_17_12_ },
    { &KinematicsSolver::calc_d_SX_d_t_18_1_, &KinematicsSolver::calc_d_SX_d_t_18_2_, &KinematicsSolver::calc_d_SX_d_t_18_3_, &KinematicsSolver::calc_d_SX_d_t_18_4_, &KinematicsSolver::calc_d_SX_d_t_18_5_, &KinematicsSolver::calc_d_SX_d_t_18_6_, &KinematicsSolver::calc_d_SX_d_t_18_7_, &KinematicsSolver::calc_d_SX_d_t_18_8_, &KinematicsSolver::calc_d_SX_d_t_18_9_, &KinematicsSolver::calc_d_SX_d_t_18_10_, &KinematicsSolver::calc_d_SX_d_t_18_11_, &KinematicsSolver::calc_d_SX_d_t_18_12_ },
    { &KinematicsSolver::calc_d_SX_d_t_19_1_, &KinematicsSolver::calc_d_SX_d_t_19_2_, &KinematicsSolver::calc_d_SX_d_t_19_3_, &KinematicsSolver::calc_d_SX_d_t_19_4_, &KinematicsSolver::calc_d_SX_d_t_19_5_, &KinematicsSolver::calc_d_SX_d_t_19_6_, &KinematicsSolver::calc_d_SX_d_t_19_7_, &KinematicsSolver::calc_d_SX_d_t_19_8_, &KinematicsSolver::calc_d_SX_d_t_19_9_, &KinematicsSolver::calc_d_SX_d_t_19_10_, &KinematicsSolver::calc_d_SX_d_t_19_11_, &KinematicsSolver::calc_d_SX_d_t_19_12_ },
    { &KinematicsSolver::calc_d_SX_d_t_20_1_, &KinematicsSolver::calc_d_SX_d_t_20_2_, &KinematicsSolver::calc_d_SX_d_t_20_3_, &KinematicsSolver::calc_d_SX_d_t_20_4_, &KinematicsSolver::calc_d_SX_d_t_20_5_, &KinematicsSolver::calc_d_SX_d_t_20_6_, &KinematicsSolver::calc_d_SX_d_t_20_7_, &KinematicsSolver::calc_d_SX_d_t_20_8_, &KinematicsSolver::calc_d_SX_d_t_20_9_, &KinematicsSolver::calc_d_SX_d_t_20_10_, &KinematicsSolver::calc_d_SX_d_t_20_11_, &KinematicsSolver::calc_d_SX_d_t_20_12_ },
    { &KinematicsSolver::calc_d_SX_d_t_21_1_, &KinematicsSolver::calc_d_SX_d_t_21_2_, &KinematicsSolver::calc_d_SX_d_t_21_3_, &KinematicsSolver::calc_d_SX_d_t_21_4_, &KinematicsSolver::calc_d_SX_d_t_21_5_, &KinematicsSolver::calc_d_SX_d_t_21_6_, &KinematicsSolver::calc_d_SX_d_t_21_7_, &KinematicsSolver::calc_d_SX_d_t_21_8_, &KinematicsSolver::calc_d_SX_d_t_21_9_, &KinematicsSolver::calc_d_SX_d_t_21_10_, &KinematicsSolver::calc_d_SX_d_t_21_11_, &KinematicsSolver::calc_d_SX_d_t_21_12_ },
    { &KinematicsSolver::calc_d_SX_d_t_22_1_, &KinematicsSolver::calc_d_SX_d_t_22_2_, &KinematicsSolver::calc_d_SX_d_t_22_3_, &KinematicsSolver::calc_d_SX_d_t_22_4_, &KinematicsSolver::calc_d_SX_d_t_22_5_, &KinematicsSolver::calc_d_SX_d_t_22_6_, &KinematicsSolver::calc_d_SX_d_t_22_7_, &KinematicsSolver::calc_d_SX_d_t_22_8_, &KinematicsSolver::calc_d_SX_d_t_22_9_, &KinematicsSolver::calc_d_SX_d_t_22_10_, &KinematicsSolver::calc_d_SX_d_t_22_11_, &KinematicsSolver::calc_d_SX_d_t_22_12_ },
    { &KinematicsSolver::calc_d_SX_d_t_23_1_, &KinematicsSolver::calc_d_SX_d_t_23_2_, &KinematicsSolver::calc_d_SX_d_t_23_3_, &KinematicsSolver::calc_d_SX_d_t_23_4_, &KinematicsSolver::calc_d_SX_d_t_23_5_, &KinematicsSolver::calc_d_SX_d_t_23_6_, &KinematicsSolver::calc_d_SX_d_t_23_7_, &KinematicsSolver::calc_d_SX_d_t_23_8_, &KinematicsSolver::calc_d_SX_d_t_23_9_, &KinematicsSolver::calc_d_SX_d_t_23_10_, &KinematicsSolver::calc_d_SX_d_t_23_11_, &KinematicsSolver::calc_d_SX_d_t_23_12_ }
  };
  
  
  // --- pd_ud_pd_t 12 ---
  inline static constexpr Mfn pdud_tbl[12] = {
    &KinematicsSolver::calc_pd_ud_pd_t_1_, &KinematicsSolver::calc_pd_ud_pd_t_2_, &KinematicsSolver::calc_pd_ud_pd_t_3_, &KinematicsSolver::calc_pd_ud_pd_t_4_, &KinematicsSolver::calc_pd_ud_pd_t_5_, &KinematicsSolver::calc_pd_ud_pd_t_6_, &KinematicsSolver::calc_pd_ud_pd_t_7_, &KinematicsSolver::calc_pd_ud_pd_t_8_, &KinematicsSolver::calc_pd_ud_pd_t_9_, &KinematicsSolver::calc_pd_ud_pd_t_10_, &KinematicsSolver::calc_pd_ud_pd_t_11_, &KinematicsSolver::calc_pd_ud_pd_t_12_
  };
  
  
  //aqd
  inline static constexpr Mfn aqd_tbl[27] = {
    &KinematicsSolver::calc_aqd_1_, &KinematicsSolver::calc_aqd_2_, &KinematicsSolver::calc_aqd_3_, &KinematicsSolver::calc_aqd_4_,
    &KinematicsSolver::calc_aqd_5_, &KinematicsSolver::calc_aqd_6_, &KinematicsSolver::calc_aqd_7_, &KinematicsSolver::calc_aqd_8_,
    &KinematicsSolver::calc_aqd_9_, &KinematicsSolver::calc_aqd_10_, &KinematicsSolver::calc_aqd_11_, &KinematicsSolver::calc_aqd_12_,
    &KinematicsSolver::calc_aqd_13_, &KinematicsSolver::calc_aqd_14_, &KinematicsSolver::calc_aqd_15_, &KinematicsSolver::calc_aqd_16_,
    &KinematicsSolver::calc_aqd_17_, &KinematicsSolver::calc_aqd_18_, &KinematicsSolver::calc_aqd_19_, &KinematicsSolver::calc_aqd_20_,
    &KinematicsSolver::calc_aqd_21_, &KinematicsSolver::calc_aqd_22_, &KinematicsSolver::calc_aqd_23_, &KinematicsSolver::calc_aqd_24_,
    &KinematicsSolver::calc_aqd_25_, &KinematicsSolver::calc_aqd_26_, &KinematicsSolver::calc_aqd_27_};
  
  
}; 




