#include "cooperative_transportation_4ws_backstepping/kinematics_solver.hpp"
#include "cooperative_transportation_4ws_backstepping/initial.hpp"
#include "cooperative_transportation_4ws_backstepping/mathFunc.h"
#include <array>
#include <iostream>

double KinematicsSolver::calc_pd_ud_pd_X_7_5_()
{
double ret;
ret = -(((-((calc_alpha_3_3_()*calc_alpha_7_2_() - calc_alpha_3_2_()*calc_alpha_7_3_())*(w1*calc_alpha_2_1_() - w2)) + calc_alpha_2_2_()*(calc_alpha_7_3_()*(-(w1*calc_alpha_3_1_()) + w3) + calc_alpha_3_3_()*(w1*calc_alpha_7_1_() - w7)) + calc_alpha_2_3_()*(calc_alpha_7_2_()*(w1*calc_alpha_3_1_() - w3) + calc_alpha_3_2_()*(-(w1*calc_alpha_7_1_()) + w7)))*(-(calc_alpha_3_3_()*calc_pd_alpha2_pd_X_2_5_()) + calc_alpha_3_2_()*calc_pd_alpha2_pd_X_3_5_() + calc_alpha_2_3_()*calc_pd_alpha3_pd_X_2_5_() - calc_alpha_2_2_()*calc_pd_alpha3_pd_X_3_5_()))/(Power(calc_alpha_2_3_()*calc_alpha_3_2_() - calc_alpha_2_2_()*calc_alpha_3_3_(),2)*calc_alpha_7_6_())) - ((-((calc_alpha_3_3_()*calc_alpha_7_2_() - calc_alpha_3_2_()*calc_alpha_7_3_())*(w1*calc_alpha_2_1_() - w2)) + calc_alpha_2_2_()*(calc_alpha_7_3_()*(-(w1*calc_alpha_3_1_()) + w3) + calc_alpha_3_3_()*(w1*calc_alpha_7_1_() - w7)) + calc_alpha_2_3_()*(calc_alpha_7_2_()*(w1*calc_alpha_3_1_() - w3) + calc_alpha_3_2_()*(-(w1*calc_alpha_7_1_()) + w7)))*calc_pd_alpha7_pd_X_4_5_())/((calc_alpha_2_3_()*calc_alpha_3_2_() - calc_alpha_2_2_()*calc_alpha_3_3_())*Power(calc_alpha_7_6_(),2)) + ((calc_alpha_7_3_()*(-(w1*calc_alpha_3_1_()) + w3) + calc_alpha_3_3_()*(w1*calc_alpha_7_1_() - w7))*calc_pd_alpha2_pd_X_2_5_() + (calc_alpha_7_2_()*(w1*calc_alpha_3_1_() - w3) + calc_alpha_3_2_()*(-(w1*calc_alpha_7_1_()) + w7))*calc_pd_alpha2_pd_X_3_5_() - (w1*calc_alpha_2_1_() - w2)*(-(calc_alpha_7_3_()*calc_pd_alpha3_pd_X_2_5_()) + calc_alpha_7_2_()*calc_pd_alpha3_pd_X_3_5_() + calc_alpha_3_3_()*calc_pd_alpha7_pd_X_2_5_() - calc_alpha_3_2_()*calc_pd_alpha7_pd_X_3_5_()) - (calc_alpha_3_3_()*calc_alpha_7_2_() - calc_alpha_3_2_()*calc_alpha_7_3_())*(w1*calc_pd_alpha2_pd_X_1_5_() - calc_pd_W_pd_X_2_5_()) + calc_alpha_2_2_()*((w1*calc_alpha_7_1_() - w7)*calc_pd_alpha3_pd_X_3_5_() + (-(w1*calc_alpha_3_1_()) + w3)*calc_pd_alpha7_pd_X_3_5_() + calc_alpha_7_3_()*(-(w1*calc_pd_alpha3_pd_X_1_5_()) + calc_pd_W_pd_X_3_5_()) + calc_alpha_3_3_()*(w1*calc_pd_alpha7_pd_X_1_5_() - calc_pd_W_pd_X_7_5_())) + calc_alpha_2_3_()*((-(w1*calc_alpha_7_1_()) + w7)*calc_pd_alpha3_pd_X_2_5_() + (w1*calc_alpha_3_1_() - w3)*calc_pd_alpha7_pd_X_2_5_() + calc_alpha_7_2_()*(w1*calc_pd_alpha3_pd_X_1_5_() - calc_pd_W_pd_X_3_5_()) + calc_alpha_3_2_()*(-(w1*calc_pd_alpha7_pd_X_1_5_()) + calc_pd_W_pd_X_7_5_())))/((calc_alpha_2_3_()*calc_alpha_3_2_() - calc_alpha_2_2_()*calc_alpha_3_3_())*calc_alpha_7_6_());
return ret;
}
