#include "cooperative_transportation_4ws_backstepping/kinematics_solver.hpp"
#include "cooperative_transportation_4ws_backstepping/initial.hpp"
#include "cooperative_transportation_4ws_backstepping/mathFunc.h"
#include <array>
#include <iostream>

double KinematicsSolver::calc_thetap2d_2_1_()
{
double ret;
ret = -(l3*Power(lv + 2*l3*Cos(Thetap3 - thetap4d),2)*Sin(Thetap3 - thetap4d)*(w1*(1 - sr.Cs*sr.d)*Sec(Thetap0)*(-((sr.Cs*Cos(Thetap0))/(1 - sr.Cs*sr.d)) + ((Cos(x_old[6] + Thetap2 - Thetap3) + Sin(x_old[8])*Sin(x_old[6] - x_old[8] + Thetap2 - Thetap3))*(Cos(x_old[4] - x_old[6] + Thetap1 - Thetap2)*Sin(x_old[4] - Thetap0 + Thetap1) + Sin(x_old[4] - x_old[6] + Thetap1 - Thetap2)*(Cos(x_old[4] - Thetap0 + Thetap1) + 2*Sin(x_old[4] - Thetap0 + Thetap1)*Tan(x_old[4]))) + (Cos(x_old[6] - x_old[8] + Thetap2 - Thetap3)*Sin(x_old[8]) - Sin(x_old[6] + Thetap2 - Thetap3))*(-(Sin(x_old[4] - Thetap0 + Thetap1)*Sin(x_old[4] - x_old[6] + Thetap1 - Thetap2)) + Cos(x_old[4] - x_old[6] + Thetap1 - Thetap2)*(Cos(x_old[4] - Thetap0 + Thetap1) + 2*Sin(x_old[4] - Thetap0 + Thetap1)*Tan(x_old[4])) - 2*(Cos(x_old[4] - x_old[6] + Thetap1 - Thetap2)*Sin(x_old[4] - Thetap0 + Thetap1) + Sin(x_old[4] - x_old[6] + Thetap1 - Thetap2)*(Cos(x_old[4] - Thetap0 + Thetap1) + 2*Sin(x_old[4] - Thetap0 + Thetap1)*Tan(x_old[4])))*Tan(x_old[6])))/l3) - dthetap4d))/(2.*Power(l2,3)*Sqrt(1 - Power(lv + 2*l3*Cos(Thetap3 - thetap4d),2)/(16.*Power(l2,2)))*(Power(lv + 2*l3*Cos(Thetap3 - thetap4d),2)/Power(l2,2) + 16*(1 - Power(lv + 2*l3*Cos(Thetap3 - thetap4d),2)/(16.*Power(l2,2))))) - (8*l3*Sqrt(1 - Power(lv + 2*l3*Cos(Thetap3 - thetap4d),2)/(16.*Power(l2,2)))*Sin(Thetap3 - thetap4d)*(w1*(1 - sr.Cs*sr.d)*Sec(Thetap0)*(-((sr.Cs*Cos(Thetap0))/(1 - sr.Cs*sr.d)) + ((Cos(x_old[6] + Thetap2 - Thetap3) + Sin(x_old[8])*Sin(x_old[6] - x_old[8] + Thetap2 - Thetap3))*(Cos(x_old[4] - x_old[6] + Thetap1 - Thetap2)*Sin(x_old[4] - Thetap0 + Thetap1) + Sin(x_old[4] - x_old[6] + Thetap1 - Thetap2)*(Cos(x_old[4] - Thetap0 + Thetap1) + 2*Sin(x_old[4] - Thetap0 + Thetap1)*Tan(x_old[4]))) + (Cos(x_old[6] - x_old[8] + Thetap2 - Thetap3)*Sin(x_old[8]) - Sin(x_old[6] + Thetap2 - Thetap3))*(-(Sin(x_old[4] - Thetap0 + Thetap1)*Sin(x_old[4] - x_old[6] + Thetap1 - Thetap2)) + Cos(x_old[4] - x_old[6] + Thetap1 - Thetap2)*(Cos(x_old[4] - Thetap0 + Thetap1) + 2*Sin(x_old[4] - Thetap0 + Thetap1)*Tan(x_old[4])) - 2*(Cos(x_old[4] - x_old[6] + Thetap1 - Thetap2)*Sin(x_old[4] - Thetap0 + Thetap1) + Sin(x_old[4] - x_old[6] + Thetap1 - Thetap2)*(Cos(x_old[4] - Thetap0 + Thetap1) + 2*Sin(x_old[4] - Thetap0 + Thetap1)*Tan(x_old[4])))*Tan(x_old[6])))/l3) - dthetap4d))/(l2*(Power(lv + 2*l3*Cos(Thetap3 - thetap4d),2)/Power(l2,2) + 16*(1 - Power(lv + 2*l3*Cos(Thetap3 - thetap4d),2)/(16.*Power(l2,2))))) + dthetap4d;
return ret;
}
