#include "cooperative_transportation_4ws_backstepping/kinematics_solver.hpp"
#include "cooperative_transportation_4ws_backstepping/initial.hpp"
#include "cooperative_transportation_4ws_backstepping/mathFunc.h"
#include <array>
#include <iostream>

double KinematicsSolver::calc_thetap5d_2_1_()
{
double ret;
ret = -(l3*Power(lv + 2*l3*Cos(Thetap6 - thetap7d),2)*Sin(Thetap6 - thetap7d)*(w1*(1 - sr.Cs*sr.d)*Sec(Thetap0)*(-((sr.Cs*Cos(Thetap0))/(1 - sr.Cs*sr.d)) + (Sec(x_old[14])*(-(Cos(x_old[12] - x_old[14] + Thetap5 - Thetap6)*(-2*Cos(x_old[12] - Thetap0 + Thetap5)*Sec(x_old[4])*Sin(PAI/6. - Thetap0 + Thetap1)*Sin(x_old[4] - Thetap0 + Thetap1) - (1 - 2*Cos(PAI/6. - Thetap0 + Thetap1)*Sec(x_old[4])*Sin(x_old[4] - Thetap0 + Thetap1))*Sin(x_old[12] - Thetap0 + Thetap5))) + Sin(x_old[12] - x_old[14] + Thetap5 - Thetap6)*(Cos(x_old[12] - Thetap0 + Thetap5)*(1 - 2*Cos(PAI/6. - Thetap0 + Thetap1)*Sec(x_old[4])*Sin(x_old[4] - Thetap0 + Thetap1)) - 2*Sec(x_old[4])*Sin(PAI/6. - Thetap0 + Thetap1)*Sin(x_old[4] - Thetap0 + Thetap1)*Sin(x_old[12] - Thetap0 + Thetap5) - 2*(-2*Cos(x_old[12] - Thetap0 + Thetap5)*Sec(x_old[4])*Sin(PAI/6. - Thetap0 + Thetap1)*Sin(x_old[4] - Thetap0 + Thetap1) - (1 - 2*Cos(PAI/6. - Thetap0 + Thetap1)*Sec(x_old[4])*Sin(x_old[4] - Thetap0 + Thetap1))*Sin(x_old[12] - Thetap0 + Thetap5))*Tan(x_old[12]))))/l3) - dthetap7d))/(2.*Power(l2,3)*Sqrt(1 - Power(lv + 2*l3*Cos(Thetap6 - thetap7d),2)/(16.*Power(l2,2)))*(Power(lv + 2*l3*Cos(Thetap6 - thetap7d),2)/Power(l2,2) + 16*(1 - Power(lv + 2*l3*Cos(Thetap6 - thetap7d),2)/(16.*Power(l2,2))))) - (8*l3*Sqrt(1 - Power(lv + 2*l3*Cos(Thetap6 - thetap7d),2)/(16.*Power(l2,2)))*Sin(Thetap6 - thetap7d)*(w1*(1 - sr.Cs*sr.d)*Sec(Thetap0)*(-((sr.Cs*Cos(Thetap0))/(1 - sr.Cs*sr.d)) + (Sec(x_old[14])*(-(Cos(x_old[12] - x_old[14] + Thetap5 - Thetap6)*(-2*Cos(x_old[12] - Thetap0 + Thetap5)*Sec(x_old[4])*Sin(PAI/6. - Thetap0 + Thetap1)*Sin(x_old[4] - Thetap0 + Thetap1) - (1 - 2*Cos(PAI/6. - Thetap0 + Thetap1)*Sec(x_old[4])*Sin(x_old[4] - Thetap0 + Thetap1))*Sin(x_old[12] - Thetap0 + Thetap5))) + Sin(x_old[12] - x_old[14] + Thetap5 - Thetap6)*(Cos(x_old[12] - Thetap0 + Thetap5)*(1 - 2*Cos(PAI/6. - Thetap0 + Thetap1)*Sec(x_old[4])*Sin(x_old[4] - Thetap0 + Thetap1)) - 2*Sec(x_old[4])*Sin(PAI/6. - Thetap0 + Thetap1)*Sin(x_old[4] - Thetap0 + Thetap1)*Sin(x_old[12] - Thetap0 + Thetap5) - 2*(-2*Cos(x_old[12] - Thetap0 + Thetap5)*Sec(x_old[4])*Sin(PAI/6. - Thetap0 + Thetap1)*Sin(x_old[4] - Thetap0 + Thetap1) - (1 - 2*Cos(PAI/6. - Thetap0 + Thetap1)*Sec(x_old[4])*Sin(x_old[4] - Thetap0 + Thetap1))*Sin(x_old[12] - Thetap0 + Thetap5))*Tan(x_old[12]))))/l3) - dthetap7d))/(l2*(Power(lv + 2*l3*Cos(Thetap6 - thetap7d),2)/Power(l2,2) + 16*(1 - Power(lv + 2*l3*Cos(Thetap6 - thetap7d),2)/(16.*Power(l2,2))))) + dthetap7d;
return ret;
}
